import 'eslint-plugin-only-warn'

import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript'
import { defineConfig } from 'eslint/config'

import typescript from '@typescript-eslint/parser'
import vitestPlugin from '@vitest/eslint-plugin'
import importX from 'eslint-plugin-import-x'
import tsPaths from 'eslint-plugin-paths'
import perfectionist from 'eslint-plugin-perfectionist'
import prettier from 'eslint-plugin-prettier'
import storybookPlugin from 'eslint-plugin-storybook'
import globals from 'globals'
import tseslint from 'typescript-eslint'

const EXT = {
  COMMONJS: '**/*.cjs',
  CSS: '**/*.{css,scss,sass,less}',
  DEFINITION_FILES: '**/*.{d.ts,tsbuildinfo}',
  HTML: '**/*.{htm,html,xml,xhtml}',
  JS: '**/*.{js,jsx}',
  JSON: '**/*.{json,json5,jsonc}',
  MD: '**/*.{md,mdx,markdown}',
  // `.mts` is the extension this config and `vitest.config.mts` are written in. It was missing — the
  // list said `mtsx`, which is not an extension anything uses — so those two files were not linted or
  // formatted at all, while `**/*.{ts,tsx}` did not reach them either.
  MODULE: '**/*.{mjs,mjsx,mts}',
  STORYBOOK: '**/*.{stories,story}.{js,jsx,ts,tsx}',
  TEST: '**/*.{spec,test,cy}.{js,ts,jsx,tsx}',
  TS: '**/*.{ts,tsx}',
  TYPE_DEFINITION: '**/types/**',
  YML: '**/*.{yml,yaml}',
}

const ignoresConfig = defineConfig({
  ignores: [
    '**/node_modules/**',
    '**/coverage/**',
    '**/build/**',
    '**/public/**',
    '**/dist/**',
    // Build output of `pnpm build-storybook`, gitignored and generated wholesale. It is not in
    // the gate's lint stage, but `pnpm lint` runs `eslint --fix .` and that walked the entire
    // bundle.
    '**/storybook-static/**',
    // Astro's build cache, which holds generated output in both spellings. `.gitignore` covers
    // `docs/.astro/` and not the nested `docs/docs/.astro/`, and without this both were parsed as
    // JavaScript — `pnpm lint` stopped on their JSON with `Unexpected token :`.
    '**/.astro/**',
    '**/.vscode/**',
    '**/.github/**',
    '**/.next/**',
    '**/.turbo/**',
    '**/.vercel/**',
    '**/.output/**',
    '**/.yarn/**',
    '**/.yarn-cache/**',
    '**/.yarnrc.yml',
    '**/.yarnrc',
    '**/yarn.lock',
    '**/package.json',
    '**/package-lock.json',
    '**/tsconfig*.json',
    '**/pnpm-lock.yaml',
    '**/npm-shrinkwrap.json',
    '**/lerna-debug.log',
    '**/lerna.json',
    '**/tsconfig*.tsbuildinfo',
    '**/*.d.ts',
    '**/*.css',
    // A recorded measurement, not source: `pnpm css:snapshot` writes it.
    '**/css-snapshot/structure.json',
    // Generated by `pnpm docs:prepare` from the keyframe catalog and `package.json`, so it is output in the
    // same sense `dist` is. Found the moment `docs/src` joined the lint stage — the linter tried to parse
    // `version.json` as JavaScript.
    '**/data/**',
    // Generated output a harness writes beside itself, not source: the Vite fixture and its builds,
    // and the scratch corpora (also gitignored).
    //
    // Deliberately **not** `**/scripts/**`, which is what this used to be. ESLint 9 *errors* when a
    // path it is handed is entirely ignored, and the gate's lint stage is handed `scripts` — so the
    // ignore turned the stage into a failure before it checked anything, and `pnpm check` stopped
    // there with the ten stages below it unrun. Measured 2026-09-14. The harnesses under `scripts/`
    // are source and are linted again; only these are output.
    '**/scripts/tmp-*/**',
    '**/scripts/.*-*/**',
    '**/scripts/vite-check/**',
  ],
})

const vitestConfig = defineConfig({
  extends: [vitestPlugin.configs.recommended],
  files: [EXT.JS, EXT.COMMONJS, EXT.MODULE, EXT.TEST],
  ignores: [EXT.DEFINITION_FILES, EXT.TYPE_DEFINITION],
  languageOptions: {
    globals: globals.vitest,
  },
  rules: {
    ...vitestPlugin.configs.recommended.rules,
    'vitest/expect-expect': 'off',
  },
})

const importConfig = defineConfig({
  extends: [importX.flatConfigs.typescript as any],
  files: [EXT.JS, EXT.MODULE, EXT.COMMONJS, EXT.TS],
  ignores: ['**/*.d.ts'],
  languageOptions: {
    parser: typescript,
    parserOptions: {
      ecmaFeatures: { jsx: true },
      ecmaVersion: 'latest',
    },
  },
  plugins: { typescript },
  rules: {
    'import-x/no-cycle': ['warn', { maxDepth: '∞' }],
  },
  settings: {
    'import-x/extensions': ['.js', '.jsx', '.ts', '.tsx'],
    'import-x/ignore': ['node_modules', '\\.(coffee|scss|css|less|hbs|svg)$'],
    'import-x/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import-x/resolver-next': [
      createTypeScriptImportResolver({
        alwaysTryTypes: true,
        project: './tsconfig.json',
      }),
    ],
  },
})

const typescriptConfig = defineConfig({
  extends: [tseslint.configs.eslintRecommended],
  files: [EXT.TS],
  ignores: [EXT.DEFINITION_FILES, EXT.TYPE_DEFINITION, EXT.TEST],
  languageOptions: {
    globals: globals.browser,
    parser: tseslint.parser,
    parserOptions: {
      ecmaFeatures: { jsx: true },
      projectService: true,
    },
  },
  plugins: { 'ts-paths': tsPaths },
  rules: {
    'ts-paths/alias': ['warn'],
  },
})

const perfectionistConfig = defineConfig({
  // JSON and YAML are deliberately absent. Nothing registers a parser or language for those
  // extensions, so ESLint falls back to its default JavaScript language and fails to parse them at
  // all — `vercel.json` and `pnpm-workspace.yaml` are the two that `eslint --fix .` reached, at
  // `Unexpected token :` and `Unexpected token .`. Sorting them would mean bringing in
  // `@eslint/json` (and a YAML parser) first; until then this list is what is linted, while the
  // extension entries stay in `EXT` as the dictionary the rest of the config reads.
  files: [EXT.COMMONJS, EXT.JS, EXT.MODULE, EXT.TS],
  ignores: ['**/*.d.ts'],
  plugins: { perfectionist },
  rules: {
    ...perfectionist.configs['recommended-natural'].rules,
    'perfectionist/sort-exports': [
      'warn',
      {
        fallbackSort: { order: 'asc', type: 'alphabetical' },
        groups: ['type-export', ['value-export', 'unknown']],
        partitionByNewLine: true,
        type: 'natural',
      },
    ],
    'perfectionist/sort-imports': [
      'warn',
      {
        fallbackSort: { order: 'asc', type: 'alphabetical' },
        groups: [
          ['type-builtin', 'type-subpath', 'type-external'],
          ['type-internal', 'type-parent', 'type-sibling', 'type-index'],
          ['named-type-builtin', 'named-type-subpath', 'named-type-external'],
          [
            'named-type-internal',
            'named-type-parent',
            'named-type-sibling',
            'named-type-index',
          ],
          ['ts-equals-import'],
          [
            'named-value-builtin',
            'named-value-subpath',
            'named-value-external',
          ],
          ['named-value-internal'],
          ['named-value-parent', 'named-value-sibling', 'named-value-index'],
          ['value-builtin', 'value-subpath', 'value-external'],
          ['value-internal'],
          ['value-parent', 'value-sibling', 'value-index'],
          ['value-side-effect', 'value-side-effect-style'],
          ['require-import'],
          ['unknown'],
        ],
        type: 'natural',
      },
    ],
  },
})

const storybookConfig = defineConfig({
  extends: storybookPlugin.configs['flat/recommended'] as any,
  files: [EXT.STORYBOOK],
  languageOptions: {
    globals: globals.browser,
  },
  plugins: { storybookPlugin: storybookPlugin as any },
})

// Reads the options from `.prettierrc` rather than restating them here, so the file stays the
// single source of truth. Kept last: it owns formatting, and nothing after it should re-enable
// a rule that disagrees with Prettier.
const prettierConfig = defineConfig({
  files: [EXT.JS, EXT.MODULE, EXT.COMMONJS, EXT.TS],
  ignores: [EXT.DEFINITION_FILES, EXT.TYPE_DEFINITION],
  plugins: { prettier },
  rules: {
    'prettier/prettier': 'warn',
  },
})

export default defineConfig([
  ignoresConfig,
  vitestConfig,
  importConfig,
  typescriptConfig,
  perfectionistConfig,
  storybookConfig,
  prettierConfig,
])
