import type { Attribute, Collection, PropertyVariables } from '@/types'

import { aspectRatio } from '@/composition/aspect-ratio'
import { backdropFilter } from '@/composition/backdrop-filter'
import { backdropFilterDropShadow } from '@/composition/backdrop-filter-drop-shadow'
import { background } from '@/composition/background'
import { backgroundPosition, backgroundPositionX, backgroundPositionY } from '@/composition/background-position'
import { backgroundRepeat } from '@/composition/background-repeat'
import { backgroundSize } from '@/composition/background-size'
import { border } from '@/composition/border'
import { borderBlock } from '@/composition/border-block'
import { borderBlockEnd } from '@/composition/border-block-end'
import { borderBlockRadius } from '@/composition/border-block-radius'
import { borderBlockStart } from '@/composition/border-block-start'
import { borderBottom } from '@/composition/border-bottom'
import { borderImage } from '@/composition/border-image'
import { borderImageOutset, borderImageOutsetX, borderImageOutsetY } from '@/composition/border-image-outset'
import { borderImageRepeat } from '@/composition/border-image-repeat'
import { borderInline } from '@/composition/border-inline'
import { borderInlineEnd } from '@/composition/border-inline-end'
import { borderInlineRadius } from '@/composition/border-inline-radius'
import { borderInlineStart } from '@/composition/border-inline-start'
import { borderLeft } from '@/composition/border-left'
import { borderRadius } from '@/composition/border-radius'
import { borderRight } from '@/composition/border-right'
import { borderTop } from '@/composition/border-top'
import { boxShadow } from '@/composition/box-shadow'
import { boxShadowInset } from '@/composition/box-shadow-inset'
import { columnRule } from '@/composition/column-rule'
import { columns } from '@/composition/columns'
import { filter } from '@/composition/filter'
import { filterDropShadow } from '@/composition/filter-drop-shadow'
import { flex } from '@/composition/flex'
import { flexFlow } from '@/composition/flex-flow'
import { font } from '@/composition/font'
import { fontSynthesis } from '@/composition/font-synthesis'
import { grid } from '@/composition/grid'
import { gridColumn } from '@/composition/grid-column'
import { gridRow } from '@/composition/grid-row'
import { hyphenateLimitChars } from '@/composition/hyphenate-limit-chars'
import { inset } from '@/composition/inset'
import { insetBlock } from '@/composition/inset-block'
import { insetInline } from '@/composition/inset-inline'
import { listStyle } from '@/composition/list-style'
import { margin } from '@/composition/margin'
import { marginBlock } from '@/composition/margin-block'
import { marginInline } from '@/composition/margin-inline'
import { marker } from '@/composition/marker'
import { maskBorderOutset, maskBorderOutsetX, maskBorderOutsetY } from '@/composition/mask-border-outset'
import { maskBorderRepeat } from '@/composition/mask-border-repeat'
import { maskBorderSlice, maskBorderSliceX, maskBorderSliceY } from '@/composition/mask-border-slice'
import { maskPosition } from '@/composition/mask-position'
import { objectPosition, objectPositionX, objectPositionY } from '@/composition/object-position'
import { offsetAnchor, offsetAnchorX, offsetAnchorY } from '@/composition/offset-anchor'
import { offsetPositionX, offsetPositionY } from '@/composition/offset-position'
import { outline } from '@/composition/outline'
import { overflow } from '@/composition/overflow'
import { overscrollBehavior } from '@/composition/overscroll-behavior'
import { padding } from '@/composition/padding'
import { paddingBlock } from '@/composition/padding-block'
import { paddingInline } from '@/composition/padding-inline'
import { textShadow } from '@/composition/text-shadow'
import {
  matrix,
  matrix3d,
  perspective,
  rotate3d,
  scale3d,
  skew,
  transform,
  translate,
  translate3d,
} from '@/composition/transform'
import { css } from '@/helpers/css'

export const propertyVariables: Collection<PropertyVariables> = {
  '.animate': {
    '--jumi-accent-color': 'auto',
    '--jumi-align-content': 'normal',
    '--jumi-align-items': 'normal',
    '--jumi-align-self': 'auto',
    '--jumi-alignment-baseline': 'baseline',
    '--jumi-all': 'initial',
    '--jumi-anchor-name': 'none',
    '--jumi-appearance': 'none',
    '--jumi-aspect-ratio': aspectRatio,
    '--jumi-aspect-ratio-height': 'auto',
    '--jumi-aspect-ratio-width': 'auto',
    '--jumi-backdrop-blur': css('blur', '0'),
    '--jumi-backdrop-brightness': css('brightness', '1'),
    '--jumi-backdrop-contrast': css('contrast', '1'),
    '--jumi-backdrop-drop-shadow': backdropFilterDropShadow,
    '--jumi-backdrop-drop-shadow-blur': '0',
    '--jumi-backdrop-drop-shadow-color': 'transparent',
    '--jumi-backdrop-drop-shadow-offset-x': '0',
    '--jumi-backdrop-drop-shadow-offset-y': '0',
    '--jumi-backdrop-filter': backdropFilter,
    '--jumi-backdrop-grayscale': css('grayscale', '0'),
    '--jumi-backdrop-hue-rotate': css('hue-rotate', '0deg'),
    '--jumi-backdrop-invert': css('invert', '0'),
    '--jumi-backdrop-opacity': css('opacity', '1'),
    '--jumi-backdrop-saturate': css('saturate', '1'),
    '--jumi-backdrop-sepia': css('sepia', '0'),
    '--jumi-backdrop-url': css('url'),
    '--jumi-backface-visibility': 'visible',
    '--jumi-background': background,
    '--jumi-background-attachment': 'scroll',
    '--jumi-background-blend-mode': 'normal',
    '--jumi-background-clip': 'border-box',
    '--jumi-background-color': 'transparent',
    '--jumi-background-image': 'none',
    '--jumi-background-origin': 'padding-box',
    '--jumi-background-position': backgroundPosition,
    '--jumi-background-position-x': backgroundPositionX,
    '--jumi-background-position-x-edge': 'left',
    '--jumi-background-position-x-offset': '0%',
    '--jumi-background-position-y': backgroundPositionY,
    '--jumi-background-position-y-edge': 'top',
    '--jumi-background-position-y-offset': '0%',
    '--jumi-background-repeat': backgroundRepeat,
    '--jumi-background-repeat-x': 'repeat',
    '--jumi-background-repeat-y': 'repeat',
    '--jumi-background-size': backgroundSize,
    '--jumi-background-size-height': 'auto',
    '--jumi-background-size-width': 'auto',
    '--jumi-block-size': 'auto',
    '--jumi-border': border,
    '--jumi-border-block': 'none',
    '--jumi-border-block-color': 'currentColor',
    '--jumi-border-block-end': borderBlockEnd,
    '--jumi-border-block-end-color': 'currentColor',
    '--jumi-border-block-end-radius': '0',
    '--jumi-border-block-end-style': 'none',
    '--jumi-border-block-end-width': 'medium',
    '--jumi-border-block-start': borderBlockStart,
    '--jumi-border-block-start-color': 'currentColor',
    '--jumi-border-block-start-radius': '0',
    '--jumi-border-block-start-style': 'none',
    '--jumi-border-block-start-width': 'medium',
    '--jumi-border-block-style': 'none',
    '--jumi-border-block-width': 'medium',
    '--jumi-border-bottom': borderBottom,
    '--jumi-border-bottom-color': 'currentColor',
    '--jumi-border-bottom-left-radius': '0',
    '--jumi-border-bottom-radius': '0',
    '--jumi-border-bottom-right-radius': '0',
    '--jumi-border-bottom-style': 'none',
    '--jumi-border-bottom-width': 'medium',
    '--jumi-border-collapse': 'separate',
    '--jumi-border-color': 'currentColor',
    '--jumi-border-end-end-radius': '0',
    '--jumi-border-end-start-radius': '0',
    '--jumi-border-image': borderImage,
    '--jumi-border-image-outset': borderImageOutset,
    '--jumi-border-image-outset-bottom': '0',
    '--jumi-border-image-outset-left': '0',
    '--jumi-border-image-outset-right': '0',
    '--jumi-border-image-outset-top': '0',
    '--jumi-border-image-outset-x': borderImageOutsetX,
    '--jumi-border-image-outset-y': borderImageOutsetY,
    '--jumi-border-image-repeat': borderImageRepeat,
    '--jumi-border-image-repeat-x': 'stretch',
    '--jumi-border-image-repeat-y': 'stretch',
    '--jumi-border-image-slice': '100%',
    '--jumi-border-image-source': 'none',
    '--jumi-border-image-width': '1',
    '--jumi-border-inline-color': 'currentColor',
    '--jumi-border-inline-end': borderInlineEnd,
    '--jumi-border-inline-end-color': 'currentColor',
    '--jumi-border-inline-end-radius': '0',
    '--jumi-border-inline-end-style': 'none',
    '--jumi-border-inline-end-width': 'medium',
    '--jumi-border-inline-start': borderInlineStart,
    '--jumi-border-inline-start-color': 'currentColor',
    '--jumi-border-inline-start-radius': '0',
    '--jumi-border-inline-start-style': 'none',
    '--jumi-border-inline-start-width': 'medium',
    '--jumi-border-inline-style': 'none',
    '--jumi-border-inline-width': 'medium',
    '--jumi-border-left': borderLeft,
    '--jumi-border-left-color': 'currentColor',
    '--jumi-border-left-radius': '0',
    '--jumi-border-left-style': 'none',
    '--jumi-border-left-width': 'medium',
    '--jumi-border-radius': '0',
    '--jumi-border-right': borderRight,
    '--jumi-border-right-color': 'currentColor',
    '--jumi-border-right-radius': '0',
    '--jumi-border-right-style': 'none',
    '--jumi-border-right-width': 'medium',
    '--jumi-border-spacing': '0',
    '--jumi-border-start-end-radius': '0',
    '--jumi-border-start-start-radius': '0',
    '--jumi-border-style': 'none',
    '--jumi-border-top': borderTop,
    '--jumi-border-top-color': 'currentColor',
    '--jumi-border-top-left-radius': '0',
    '--jumi-border-top-radius': '0',
    '--jumi-border-top-right-radius': '0',
    '--jumi-border-top-style': 'none',
    '--jumi-border-top-width': 'medium',
    '--jumi-border-width': 'medium',
    '--jumi-bottom': 'auto',
    '--jumi-box-decoration-break': 'slice',
    '--jumi-box-shadow': boxShadow,
    '--jumi-box-shadow-blur': '0',
    '--jumi-box-shadow-color': 'transparent',
    '--jumi-box-shadow-inset': boxShadowInset,
    '--jumi-box-shadow-inset-blur': '0',
    '--jumi-box-shadow-inset-color': 'transparent',
    '--jumi-box-shadow-inset-offset-x': '0',
    '--jumi-box-shadow-inset-offset-y': '0',
    '--jumi-box-shadow-inset-spread': '0',
    '--jumi-box-shadow-offset-x': '0',
    '--jumi-box-shadow-offset-y': '0',
    '--jumi-box-shadow-spread': '0',
    '--jumi-box-sizing': 'content-box',
    '--jumi-break-after': 'auto',
    '--jumi-break-before': 'auto',
    '--jumi-break-inside': 'auto',
    '--jumi-caption-side': 'top',
    '--jumi-caret-color': 'auto',
    '--jumi-clear': 'none',
    '--jumi-clip-path': 'none',
    '--jumi-clip-rule': 'nonzero',
    '--jumi-color': 'canvastext',
    '--jumi-color-interpolation': 'auto',
    '--jumi-color-interpolation-filters': 'linearRGB',
    '--jumi-color-scheme': 'normal',
    '--jumi-column-count': 'auto',
    '--jumi-column-fill': 'balance',
    '--jumi-column-gap': 'normal',
    '--jumi-column-rule': columnRule,
    '--jumi-column-rule-color': 'medium',
    '--jumi-column-rule-style': 'none',
    '--jumi-column-rule-width': 'currentColor',
    '--jumi-column-span': 'none',
    '--jumi-column-width': 'auto',
    '--jumi-columns': columns,
    '--jumi-contain': 'none',
    '--jumi-contain-intrinsic-block-size': 'none',
    '--jumi-contain-intrinsic-height': 'none',
    '--jumi-contain-intrinsic-inline-size': 'none',
    '--jumi-contain-intrinsic-size': 'none',
    '--jumi-contain-intrinsic-width': 'none',
    '--jumi-content': 'normal',
    '--jumi-content-visibility': 'visible',
    '--jumi-counter-increment': 'none',
    '--jumi-counter-reset': 'none',
    '--jumi-counter-set': 'none',
    '--jumi-cursor': 'auto',
    '--jumi-cx': '0',
    '--jumi-cy': '0',
    '--jumi-d': 'none',
    '--jumi-display': 'inline',
    '--jumi-display-inside': 'flow',
    '--jumi-display-outside': 'block',
    '--jumi-dominant-baseline': 'auto',
    '--jumi-empty-cells': 'show',
    '--jumi-fill': 'black',
    '--jumi-fill-opacity': '1',
    '--jumi-fill-rule': 'nonzero',
    '--jumi-filter': filter,
    '--jumi-filter-blur': css('blur', '0'),
    '--jumi-filter-brightness': css('brightness', '1'),
    '--jumi-filter-contrast': css('contrast', '1'),
    '--jumi-filter-drop-shadow': filterDropShadow,
    '--jumi-filter-drop-shadow-blur': '0',
    '--jumi-filter-drop-shadow-color': 'transparent',
    '--jumi-filter-drop-shadow-offset-x': '0',
    '--jumi-filter-drop-shadow-offset-y': '0',
    '--jumi-filter-drop-shadow-opacity': '1',
    '--jumi-filter-grayscale': css('grayscale', '0'),
    '--jumi-filter-hue-rotate': css('hue-rotate', '0deg'),
    '--jumi-filter-invert': css('invert', '0'),
    '--jumi-filter-opacity': css('opacity', '1'),
    '--jumi-filter-saturate': css('saturate', '1'),
    '--jumi-filter-sepia': css('sepia', '0'),
    '--jumi-filter-url': css('url'),
    '--jumi-flex': flex,
    '--jumi-flex-basis': 'auto',
    '--jumi-flex-direction': 'row',
    '--jumi-flex-flow': flexFlow,
    '--jumi-flex-grow': '0',
    '--jumi-flex-shrink': '1',
    '--jumi-flex-wrap': 'nowrap',
    '--jumi-float': 'none',
    '--jumi-flood-color': 'black',
    '--jumi-flood-opacity': '1',
    '--jumi-font': font,
    '--jumi-font-family': 'inherit',
    '--jumi-font-feature-settings': 'normal',
    '--jumi-font-kerning': 'auto',
    '--jumi-font-language-override': 'normal',
    '--jumi-font-optical-sizing': 'auto',
    '--jumi-font-palette': 'normal',
    '--jumi-font-size': 'medium',
    '--jumi-font-size-adjust': 'none',
    '--jumi-font-style': 'normal',
    '--jumi-font-synthesis': fontSynthesis,
    '--jumi-font-synthesis-position': 'none',
    '--jumi-font-synthesis-small-caps': 'auto',
    '--jumi-font-synthesis-style': 'auto',
    '--jumi-font-synthesis-weight': 'auto',
    '--jumi-font-variant': 'normal',
    '--jumi-font-variant-alternates': 'normal',
    '--jumi-font-variant-caps': 'normal',
    '--jumi-font-variant-east-asian': 'normal',
    '--jumi-font-variant-emoji': 'normal',
    '--jumi-font-variant-ligatures': 'normal',
    '--jumi-font-variant-numeric': 'normal',
    '--jumi-font-variant-position': 'normal',
    '--jumi-font-variation-settings': 'normal',
    '--jumi-font-weight': 'normal',
    '--jumi-forced-color-adjust': 'auto',
    '--jumi-gap': '0',
    '--jumi-grid': grid,
    '--jumi-grid-auto-columns': 'auto',
    '--jumi-grid-auto-flow': 'row',
    '--jumi-grid-auto-rows': 'auto',
    '--jumi-grid-column': gridColumn,
    '--jumi-grid-column-end': 'auto',
    '--jumi-grid-column-start': 'auto',
    '--jumi-grid-row': gridRow,
    '--jumi-grid-row-end': 'auto',
    '--jumi-grid-row-start': 'auto',
    '--jumi-grid-template-areas': 'none',
    '--jumi-grid-template-columns': 'none',
    '--jumi-grid-template-rows': 'none',
    '--jumi-hanging-punctuation': 'none',
    '--jumi-height': 'auto',
    '--jumi-hyphenate-character': 'auto',
    '--jumi-hyphenate-limit-chars': hyphenateLimitChars,
    '--jumi-hyphenate-limit-minimum-characters-after': 'auto',
    '--jumi-hyphenate-limit-minimum-characters-before': 'auto',
    '--jumi-hyphenate-limit-minimum-word-length': 'auto',
    '--jumi-hyphens': 'manual',
    '--jumi-image-orientation': 'from-image',
    '--jumi-image-rendering': 'auto',
    '--jumi-initial-letter': 'normal',
    '--jumi-inline-size': 'auto',
    '--jumi-inset': inset,
    '--jumi-inset-block': insetBlock,
    '--jumi-inset-block-end': 'auto',
    '--jumi-inset-block-start': 'auto',
    '--jumi-inset-inline': insetInline,
    '--jumi-inset-inline-end': 'auto',
    '--jumi-inset-inline-start': 'auto',
    '--jumi-justify-content': 'normal',
    '--jumi-justify-items': 'legacy',
    '--jumi-justify-self': 'auto',
    '--jumi-left': 'auto',
    '--jumi-letter-spacing': 'normal',
    '--jumi-lighting-color': 'white',
    '--jumi-line-break': 'auto',
    '--jumi-line-clamp': 'none',
    '--jumi-line-height': 'normal',
    '--jumi-list-style': listStyle,
    '--jumi-list-style-image': 'none',
    '--jumi-list-style-position': 'outside',
    '--jumi-list-style-type': 'disc',
    '--jumi-margin': margin,
    '--jumi-margin-block': marginBlock,
    '--jumi-margin-block-end': '0',
    '--jumi-margin-block-start': '0',
    '--jumi-margin-bottom': '0',
    '--jumi-margin-inline': marginInline,
    '--jumi-margin-inline-end': '0',
    '--jumi-margin-inline-start': '0',
    '--jumi-margin-left': '0',
    '--jumi-margin-right': '0',
    '--jumi-margin-top': '0',
    '--jumi-marker': marker,
    '--jumi-marker-end': 'none',
    '--jumi-marker-mid': 'none',
    '--jumi-marker-start': 'none',
    '--jumi-mask': 'none',
    '--jumi-mask-border': 'none',
    '--jumi-mask-border-mode': 'alpha',
    '--jumi-mask-border-outset': maskBorderOutset,
    '--jumi-mask-border-outset-bottom': '0',
    '--jumi-mask-border-outset-left': '0',
    '--jumi-mask-border-outset-right': '0',
    '--jumi-mask-border-outset-top': '0',
    '--jumi-mask-border-outset-x': maskBorderOutsetX,
    '--jumi-mask-border-outset-y': maskBorderOutsetY,
    '--jumi-mask-border-repeat': maskBorderRepeat,
    '--jumi-mask-border-repeat-x': 'stretch',
    '--jumi-mask-border-repeat-y': 'stretch',
    '--jumi-mask-border-slice': maskBorderSlice,
    '--jumi-mask-border-slice-bottom': '0',
    '--jumi-mask-border-slice-left': '0',
    '--jumi-mask-border-slice-right': '0',
    '--jumi-mask-border-slice-top': '0',
    '--jumi-mask-border-slice-x': maskBorderSliceX,
    '--jumi-mask-border-slice-y': maskBorderSliceY,
    '--jumi-mask-border-source': 'none',
    '--jumi-mask-border-width': 'auto',
    '--jumi-mask-clip': 'border-box',
    '--jumi-mask-composite': 'add',
    '--jumi-mask-image': 'none',
    '--jumi-mask-mode': 'match-source',
    '--jumi-mask-origin': 'border-box',
    '--jumi-mask-position': maskPosition,
    '--jumi-mask-position-x': '0%',
    '--jumi-mask-position-y': '0%',
    '--jumi-mask-repeat': 'repeat',
    '--jumi-mask-size': 'auto',
    '--jumi-mask-type': 'luminance',
    '--jumi-math-depth': '0',
    '--jumi-math-depth-add': '0',
    '--jumi-math-style': 'normal',
    '--jumi-matrix': matrix,
    '--jumi-matrix-3d': matrix3d,
    '--jumi-matrix-a': '1',
    '--jumi-matrix-a1': '1',
    '--jumi-matrix-a2': '0',
    '--jumi-matrix-a3': '0',
    '--jumi-matrix-a4': '0',
    '--jumi-matrix-b': '0',
    '--jumi-matrix-b1': '0',
    '--jumi-matrix-b2': '1',
    '--jumi-matrix-b3': '0',
    '--jumi-matrix-b4': '0',
    '--jumi-matrix-c': '0',
    '--jumi-matrix-c1': '0',
    '--jumi-matrix-c2': '0',
    '--jumi-matrix-c3': '1',
    '--jumi-matrix-c4': '0',
    '--jumi-matrix-d': '1',
    '--jumi-matrix-d1': '0',
    '--jumi-matrix-d2': '0',
    '--jumi-matrix-d3': '0',
    '--jumi-matrix-d4': '1',
    '--jumi-matrix-tx': '0',
    '--jumi-matrix-ty': '0',
    '--jumi-max-block-size': 'none',
    '--jumi-max-height': 'none',
    '--jumi-max-inline-size': 'none',
    '--jumi-max-width': 'none',
    '--jumi-min-block-size': '0',
    '--jumi-min-height': 'auto',
    '--jumi-min-inline-size': '0',
    '--jumi-min-width': 'auto',
    '--jumi-mix-blend-mode': 'normal',
    '--jumi-object-fit': 'fill',
    '--jumi-object-position': objectPosition,
    '--jumi-object-position-x': objectPositionX,
    '--jumi-object-position-x-edge': 'left',
    '--jumi-object-position-x-offset': '50%',
    '--jumi-object-position-y': objectPositionY,
    '--jumi-object-position-y-edge': 'top',
    '--jumi-object-position-y-offset': '50%',
    '--jumi-offset': 'none',
    '--jumi-offset-anchor': offsetAnchor,
    '--jumi-offset-anchor-x': offsetAnchorX,
    '--jumi-offset-anchor-x-edge': 'center',
    '--jumi-offset-anchor-x-offset': '0',
    '--jumi-offset-anchor-y': offsetAnchorY,
    '--jumi-offset-anchor-y-edge': 'center',
    '--jumi-offset-anchor-y-offset': '0',
    '--jumi-offset-distance': '0',
    '--jumi-offset-path': 'none',
    '--jumi-offset-position': 'normal',
    '--jumi-offset-position-x': offsetPositionX,
    '--jumi-offset-position-x-edge': 'left',
    '--jumi-offset-position-x-offset': '50%',
    '--jumi-offset-position-y': offsetPositionY,
    '--jumi-offset-position-y-edge': 'top',
    '--jumi-offset-position-y-offset': '50%',
    '--jumi-offset-rotate': 'auto',
    '--jumi-opacity': '1',
    '--jumi-order': '0',
    '--jumi-orphans': '2',
    '--jumi-outline': outline,
    '--jumi-outline-color': 'currentColor',
    '--jumi-outline-offset': '0',
    '--jumi-outline-style': 'none',
    '--jumi-outline-width': 'medium',
    '--jumi-overflow': overflow,
    '--jumi-overflow-anchor': 'auto',
    '--jumi-overflow-block': 'auto',
    '--jumi-overflow-clip-margin': '0px',
    '--jumi-overflow-inline': 'auto',
    '--jumi-overflow-wrap': 'normal',
    '--jumi-overflow-x': 'visible',
    '--jumi-overflow-y': 'visible',
    '--jumi-overscroll-behavior': overscrollBehavior,
    '--jumi-overscroll-behavior-block': 'auto',
    '--jumi-overscroll-behavior-inline': 'auto',
    '--jumi-overscroll-behavior-x': 'auto',
    '--jumi-overscroll-behavior-y': 'auto',
    '--jumi-padding': padding,
    '--jumi-padding-block': paddingBlock,
    '--jumi-padding-block-end': '0',
    '--jumi-padding-block-start': '0',
    '--jumi-padding-bottom': '0',
    '--jumi-padding-inline': paddingInline,
    '--jumi-padding-inline-end': '0',
    '--jumi-padding-inline-start': '0',
    '--jumi-padding-left': '0',
    '--jumi-padding-right': '0',
    '--jumi-padding-top': '0',
    '--jumi-page': 'auto',
    '--jumi-paint-order': 'normal',
    '--jumi-perspective': perspective,
    '--jumi-perspective-origin': 'center',
    '--jumi-place-content': 'normal',
    '--jumi-place-items': 'normal',
    '--jumi-place-self': 'auto',
    '--jumi-position': 'static',
    '--jumi-resize': 'none',
    '--jumi-right': 'auto',
    '--jumi-rotate': '0deg',
    '--jumi-rotate-3d': rotate3d,
    '--jumi-rotate-x': '0',
    '--jumi-rotate-y': '0',
    '--jumi-rotate-z': '1',
    '--jumi-row-gap': '0',
    '--jumi-scale': '1',
    '--jumi-scale-3d': scale3d,
    '--jumi-scale-x': '1',
    '--jumi-scale-y': '1',
    '--jumi-scale-z': '1',
    '--jumi-scroll-margin': '0',
    '--jumi-scroll-margin-block': '0',
    '--jumi-scroll-margin-block-end': '0',
    '--jumi-scroll-margin-block-start': '0',
    '--jumi-scroll-margin-bottom': '0',
    '--jumi-scroll-margin-inline': '0',
    '--jumi-scroll-margin-inline-end': '0',
    '--jumi-scroll-margin-inline-start': '0',
    '--jumi-scroll-margin-left': '0',
    '--jumi-scroll-margin-right': '0',
    '--jumi-scroll-margin-top': '0',
    '--jumi-scroll-padding': '0',
    '--jumi-scroll-padding-block': '0',
    '--jumi-scroll-padding-block-end': '0',
    '--jumi-scroll-padding-block-start': '0',
    '--jumi-scroll-padding-bottom': '0',
    '--jumi-scroll-padding-inline': '0',
    '--jumi-scroll-padding-inline-end': '0',
    '--jumi-scroll-padding-inline-start': '0',
    '--jumi-scroll-padding-left': '0',
    '--jumi-scroll-padding-right': '0',
    '--jumi-scroll-padding-top': '0',
    '--jumi-shape-outside': 'none',
    '--jumi-skew': skew,
    '--jumi-skew-x': '0deg',
    '--jumi-skew-y': '0deg',
    '--jumi-stroke': 'none',
    '--jumi-stroke-dasharray': 'none',
    '--jumi-stroke-dashoffset': '0',
    '--jumi-stroke-linecap': 'butt',
    '--jumi-stroke-linejoin': 'miter',
    '--jumi-stroke-miterlimit': '4',
    '--jumi-stroke-opacity': '1',
    '--jumi-stroke-width': '1px',
    '--jumi-table-layout': 'auto',
    '--jumi-text-align': 'baseline',
    '--jumi-text-align-last': 'auto',
    '--jumi-text-anchor': 'start',
    '--jumi-text-autospace': 'normal',
    '--jumi-text-box': 'normal',
    '--jumi-text-box-edge': 'leading',
    '--jumi-text-box-trim': 'none',
    '--jumi-text-combine-upright': 'none',
    '--jumi-text-decoration': 'none',
    '--jumi-text-decoration-color': 'currentColor',
    '--jumi-text-decoration-line': 'none',
    '--jumi-text-decoration-skip-ink': 'auto',
    '--jumi-text-decoration-style': 'solid',
    '--jumi-text-decoration-thickness': 'auto',
    '--jumi-text-emphasis': 'none',
    '--jumi-text-emphasis-color': 'currentColor',
    '--jumi-text-emphasis-position': 'over right',
    '--jumi-text-emphasis-style': 'none',
    '--jumi-text-indent': '0',
    '--jumi-text-justify': 'auto',
    '--jumi-text-orientation': 'mixed',
    '--jumi-text-overflow': 'clip',
    '--jumi-text-rendering': 'auto',
    '--jumi-text-shadow': textShadow,
    '--jumi-text-shadow-blur-radius': '0',
    '--jumi-text-shadow-color': 'currentColor',
    '--jumi-text-shadow-offset-x': '0px',
    '--jumi-text-shadow-offset-y': '0px',
    '--jumi-text-transform': 'none',
    '--jumi-text-underline-offset': 'auto',
    '--jumi-text-underline-position': 'auto',
    '--jumi-text-wrap': 'wrap',
    '--jumi-text-wrap-mode': 'wrap',
    '--jumi-text-wrap-style': 'auto',
    '--jumi-top': 'auto',
    '--jumi-transform': transform,
    '--jumi-transform-box': 'view-box',
    '--jumi-transform-origin': 'center',
    '--jumi-transform-origin-x': '50%',
    '--jumi-transform-origin-y': '50%',
    '--jumi-transform-origin-z': '0px',
    '--jumi-transform-style': 'flat',
    '--jumi-translate': '0px',
    '--jumi-translate-3d': translate3d,
    '--jumi-translate-x': translate,
    '--jumi-translate-y': translate,
    '--jumi-translate-z': '0px',
    '--jumi-user-drag': 'auto',
    '--jumi-user-select': 'auto',
    '--jumi-vertical-align': 'baseline',
    '--jumi-visibility': 'visible',
    '--jumi-white-space': 'normal',
    '--jumi-width': 'auto',
    '--jumi-word-break': 'normal',
    '--jumi-z-index': 'auto',
  },
}
