export const appearance = {
  'auto': 'auto',
  'base-select': 'base-select',
  'button': 'button',
  'checkbox': 'checkbox',
  'listbox': 'listbox',
  'menulist': 'menulist',
  'menulist-button': 'menulist-button',
  'meter': 'meter',
  'none': 'none',
  'progress-bar': 'progress-bar',
  'push-button': 'push-button',
  'radio': 'radio',
  'searchfield': 'searchfield',
  'slider-horizontal': 'slider-horizontal',
  'square-button': 'square-button',
  'textarea': 'textarea',
  'textfield': 'textfield',
} as const
