export const appearance = {
  'auto': 'auto',
  'base': 'base',
  'base-select': 'base-select',
  'button': 'button',
  'checkbox': 'checkbox',
  'listbox': 'listbox',
  'menulist': 'menulist',
  'menulist-button': 'menulist-button',
  'meter': 'meter',
  'none': 'none',
  'progress-bar': 'progress-bar',
  'radio': 'radio',
  'searchfield': 'searchfield',
  'textarea': 'textarea',
  'textfield': 'textfield',
} as const
