export const breakBefore = {
  'all': 'all',
  'always': 'always',
  'auto': 'auto',
  'avoid': 'avoid',
  'avoid-column': 'avoid-column',
  'avoid-page': 'avoid-page',
  'avoid-region': 'avoid-region',
  'column': 'column',
  'left': 'left',
  'page': 'page',
  'recto': 'recto',
  'region': 'region',
  'right': 'right',
  'verso': 'verso',
} as const
