export const justifyContent = {
  'center': 'center',
  'end': 'end',
  'flex-end': 'flex-end',
  'flex-start': 'flex-start',
  'left': 'left',
  'normal': 'normal',
  'right': 'right',
  'safe-center': 'safe center',
  'space-around': 'space-around',
  'space-between': 'space-between',
  'space-evenly': 'space-evenly',
  'start': 'start',
  'stretch': 'stretch',
  'unsafe-center': 'unsafe center',
} as const
