export const mixBlendMode = {
  'color': 'color',
  'color-burn': 'color-burn',
  'color-dodge': 'color-dodge',
  'darken': 'darken',
  'difference': 'difference',
  'exclusion': 'exclusion',
  'hard-light': 'hard-light',
  'hue': 'hue',
  'lighten': 'lighten',
  'luminosity': 'luminosity',
  'multiply': 'multiply',
  'normal': 'normal',
  'overlay': 'overlay',
  'plus-darker': 'plus-darker',
  'plus-lighter': 'plus-lighter',
  'saturation': 'saturation',
  'screen': 'screen',
  'soft-light': 'soft-light',
}
