export const positionArea = {
  'bottom': 'bottom',
  'bottom-left': 'bottom left',
  'bottom-right': 'bottom right',
  'center': 'center',
  'end': 'end',
  'left': 'left',
  'right': 'right',
  'self-end': 'self-end',
  'self-start': 'self-start',
  'span-all': 'span-all',
  'span-end': 'span-end',
  'span-self-end': 'span-self-end',
  'span-self-start': 'span-self-start',
  'span-start': 'span-start',
  'start': 'start',
  'top': 'top',
  'top-left': 'top left',
  'top-right': 'top right',
}

export const positionAreaX = {
  'center': 'center',
  'inline-end': 'inline-end',
  'inline-start': 'inline-start',
  'left': 'left',
  'right': 'right',
  'self-inline-end': 'self-inline-end',
  'self-inline-start': 'self-inline-start',
  'span-all': 'span-all',
  'span-inline-end': 'span-inline-end',
  'span-inline-start': 'span-inline-start',
  'span-left': 'span-left',
  'span-right': 'span-right',
  'span-self-inline-end': 'span-self-inline-end',
  'span-self-inline-start': 'span-self-inline-start',
  'span-x-end': 'span-x-end',
  'span-x-self-end': 'span-x-self-end',
  'span-x-self-start': 'span-x-self-start',
  'span-x-start': 'span-x-start',
  'x-end': 'x-end',
  'x-self-end': 'x-self-end',
  'x-self-start': 'x-self-start',
  'x-start': 'x-start',
}

export const positionAreaY = {
  'block-end': 'block-end',
  'block-start': 'block-start',
  'bottom': 'bottom',
  'center': 'center',
  'self-block-end': 'self-block-end',
  'self-block-start': 'self-block-start',
  'span-all': 'span-all',
  'span-block-end': 'span-block-end',
  'span-block-start': 'span-block-start',
  'span-bottom': 'span-bottom',
  'span-self-block-end': 'span-self-block-end',
  'span-self-block-start': 'span-self-block-start',
  'span-top': 'span-top',
  'span-y-end': 'span-y-end',
  'span-y-self-end': 'span-y-self-end',
  'span-y-self-start': 'span-y-self-start',
  'span-y-start': 'span-y-start',
  'top': 'top',
  'y-end': 'y-end',
  'y-self-end': 'y-self-end',
  'y-self-start': 'y-self-start',
  'y-start': 'y-start',
}
