import {
  animationRange,
  animationRangeEnd,
  animationRangeStart,
} from '@/composition/animation-range'
import { animationTimelineInset } from '@/composition/animation-timeline'
import { aspectRatio } from '@/composition/aspect-ratio'
import { backdropFilter } from '@/composition/backdrop-filter'
import { backgroundPosition, backgroundPositionX, backgroundPositionY } from '@/composition/background-position'
import { backgroundRepeat } from '@/composition/background-repeat'
import { backgroundSize } from '@/composition/background-size'
import { display } from '@/composition/display'
import { filter } from '@/composition/filter'
import {
  matrix,
  matrix3d,
  rotate,
  rotate3d,
  scale,
  scale3d,
  skew,
  transform,
  translate,
  translate3d,
} from '@/composition/transform'
import { keyframes } from '@/keyframes/property'

export const variables = {
  '--jumi-animation-composition': 'replace',
  '--jumi-animation-delay': '0s',
  '--jumi-animation-direction': 'alternate',
  '--jumi-animation-duration': '1s',
  '--jumi-animation-fill-mode': 'forwards',
  '--jumi-animation-iteration-count': '1',
  '--jumi-animation-name': keyframes,
  '--jumi-animation-play-state': 'running',
  '--jumi-animation-range': animationRange,
  '--jumi-animation-range-end': animationRangeEnd,
  '--jumi-animation-range-end-length': '100%',
  '--jumi-animation-range-end-name': 'normal',
  '--jumi-animation-range-start': animationRangeStart,
  '--jumi-animation-range-start-length': '0%',
  '--jumi-animation-range-start-name': 'normal',
  '--jumi-animation-timeline': 'auto',
  '--jumi-animation-timeline-axis': 'block',
  '--jumi-animation-timeline-inset': animationTimelineInset,
  '--jumi-animation-timeline-inset-end': 'auto',
  '--jumi-animation-timeline-inset-start': 'auto',
  '--jumi-animation-timeline-scroller': 'nearest',
  '--jumi-animation-timing-function': 'ease',
  '--jumi-aspect-ratio': aspectRatio,
  '--jumi-aspect-ratio-height': 'auto',
  '--jumi-aspect-ratio-width': 'auto',
  '--jumi-backdrop-blur': 'blur(0)',
  '--jumi-backdrop-brightness': 'brightness(1)',
  '--jumi-backdrop-contrast': 'contrast(1)',
  '--jumi-backdrop-filter': backdropFilter,
  '--jumi-backdrop-grayscale': 'grayscale(0)',
  '--jumi-backdrop-hue-rotate': 'hue-rotate(0deg)',
  '--jumi-backdrop-invert': 'invert(0)',
  '--jumi-backdrop-opacity': 'opacity(1)',
  '--jumi-backdrop-saturate': 'saturate(1)',
  '--jumi-backdrop-sepia': 'sepia(0)',
  '--jumi-backdrop-url': 'url()',
  '--jumi-background-attachment': 'scroll',
  '--jumi-background-clip': 'border-box',
  '--jumi-background-color': 'transparent',
  '--jumi-background-image': 'none',
  '--jumi-background-position': backgroundPosition,
  '--jumi-background-position-x': backgroundPositionX,
  '--jumi-background-position-x-edge': 'left',
  '--jumi-background-position-x-offset': '0%',
  '--jumi-background-position-y': backgroundPositionY,
  '--jumi-background-position-y-edge': 'top',
  '--jumi-background-position-y-offset': '0%',
  '--jumi-background-repeat': backgroundRepeat,
  '--jumi-background-repeat-x': 'no-repeat',
  '--jumi-background-repeat-y': 'no-repeat',
  '--jumi-background-size': backgroundSize,
  '--jumi-blur': 'blur(0)',
  '--jumi-border-color': 'currentColor',
  '--jumi-border-radius': '0',
  '--jumi-border-width': '0',
  '--jumi-bottom': 'auto',
  '--jumi-box-shadow': 'none',
  '--jumi-box-shadow-color': '0 0 0 0 transparent',
  '--jumi-box-shadow-offset-x': '0',
  '--jumi-box-shadow-offset-y': '0',
  '--jumi-box-shadow-opacity': '1',
  '--jumi-box-shadow-radius': '0',
  '--jumi-caret-color': 'auto',
  '--jumi-clip-path': 'none',
  '--jumi-color': 'inherit',
  '--jumi-cursor': 'auto',
  '--jumi-display': display,
  '--jumi-display-inside': 'flow',
  '--jumi-display-ouside': 'block',
  '--jumi-fill': 'currentColor',
  '--jumi-fill-opacity': '1',
  '--jumi-filter': filter,
  '--jumi-filter-brightness': 'brightness(1)',
  '--jumi-filter-contrast': 'contrast(1)',
  '--jumi-filter-drop-shadow': 'drop-shadow(0 0 0 transparent)',
  '--jumi-filter-grayscale': 'grayscale(0)',
  '--jumi-filter-hue-rotate': 'hue-rotate(0deg)',
  '--jumi-filter-invert': 'invert(0)',
  '--jumi-filter-opacity': '1',
  '--jumi-filter-saturate': 'saturate(1)',
  '--jumi-filter-sepia': 'sepia(0)',
  '--jumi-filter-url': 'url()',
  '--jumi-flex-basis': 'auto',
  '--jumi-flex-direction': 'row',
  '--jumi-flex-grow': '0',
  '--jumi-flex-shrink': '1',
  '--jumi-flex-wrap': 'nowrap',
  '--jumi-font-family': 'inherit',
  '--jumi-font-size': '1rem',
  '--jumi-font-weight': '400',
  '--jumi-gap': '0',
  '--jumi-gap-column': '0',
  '--jumi-gap-row': '0',
  '--jumi-grids-auto-columns': 'auto',
  '--jumi-grids-auto-flow': 'row',
  '--jumi-grids-auto-rows': 'auto',
  '--jumi-grids-template-areas': 'none',
  '--jumi-grids-template-columns': 'none',
  '--jumi-grids-template-rows': 'none',
  '--jumi-height': 'auto',
  '--jumi-image-rendering': 'auto',
  '--jumi-initial-letter': 'normal',
  '--jumi-inset': 'auto',
  '--jumi-inset-block': 'auto',
  '--jumi-inset-block-end': 'auto',
  '--jumi-inset-block-start': 'auto',
  '--jumi-inset-inline': 'auto',
  '--jumi-inset-inline-end': 'auto',
  '--jumi-inset-inline-start': 'auto',
  '--jumi-left': 'auto',
  '--jumi-letter-spacing': 'normal',
  '--jumi-line-height': 'normal',
  '--jumi-margin': '0',
  '--jumi-matrix': matrix,
  '--jumi-matrix-3d': matrix3d,
  '--jumi-matrix-a': '1',
  '--jumi-matrix-a1': '1',
  '--jumi-matrix-a2': '0',
  '--jumi-matrix-a3': '0',
  '--jumi-matrix-a4': '0',
  '--jumi-matrix-b': '0',
  '--jumi-matrix-b1': '0',
  '--jumi-matrix-b2': '1',
  '--jumi-matrix-b3': '0',
  '--jumi-matrix-b4': '0',
  '--jumi-matrix-c': '0',
  '--jumi-matrix-c1': '0',
  '--jumi-matrix-c2': '0',
  '--jumi-matrix-c3': '1',
  '--jumi-matrix-c4': '0',
  '--jumi-matrix-d': '1',
  '--jumi-matrix-d1': '0',
  '--jumi-matrix-d2': '0',
  '--jumi-matrix-d3': '0',
  '--jumi-matrix-d4': '1',
  '--jumi-matrix-tx': '0',
  '--jumi-matrix-ty': '0',
  '--jumi-order': '0',
  '--jumi-outline-color': 'currentColor',
  '--jumi-outline-offset': '0',
  '--jumi-outline-width': '0',
  '--jumi-perspective': 'perspective(none)',
  '--jumi-perspective-origin': 'center',
  '--jumi-right': 'auto',
  '--jumi-rotate': rotate,
  '--jumi-rotate-3d': rotate3d,
  '--jumi-rotate-3x': '0',
  '--jumi-rotate-3y': '0',
  '--jumi-rotate-3z': '0',
  '--jumi-rotate-angle': '0deg',
  '--jumi-rotate-x': 'rotateX(0deg)',
  '--jumi-rotate-y': 'rotateY(0deg)',
  '--jumi-rotate-z': 'rotateZ(0deg)',
  '--jumi-saturate': 'saturate(1)',
  '--jumi-scale': scale,
  '--jumi-scale-3d': scale3d,
  '--jumi-scale-3x': '1',
  '--jumi-scale-3y': '1',
  '--jumi-scale-3z': '1',
  '--jumi-scale-sx': '1',
  '--jumi-scale-sy': '1',
  '--jumi-scale-x': 'scaleX(1)',
  '--jumi-scale-y': 'scaleY(1)',
  '--jumi-scale-z': 'scaleZ(1)',
  '--jumi-shadow': 'none',
  '--jumi-shadow-color': '0 0 0 0 transparent',
  '--jumi-shadow-offset-x': '0',
  '--jumi-shadow-offset-y': '0',
  '--jumi-shadow-opacity': '1',
  '--jumi-shadow-radius': '0',
  '--jumi-skew': skew,
  '--jumi-skew-sx': '0',
  '--jumi-skew-sy': '0',
  '--jumi-skew-x': 'skewX(0deg)',
  '--jumi-skew-y': 'skewY(0deg)',
  '--jumi-stroke': 'none',
  '--jumi-stroke-dasharray': 'none',
  '--jumi-stroke-dashoffset': '0',
  '--jumi-stroke-width': '1',
  '--jumi-text-align': 'baseline',
  '--jumi-text-decoration': 'none',
  '--jumi-text-decoration-color': 'currentColor',
  '--jumi-text-decoration-line': 'none',
  '--jumi-text-decoration-style': 'solid',
  '--jumi-text-fill-color': 'currentColor',
  '--jumi-text-indent': '0',
  '--jumi-text-overflow': 'clip',
  '--jumi-text-rendering': 'auto',
  '--jumi-text-shadow': 'none',
  '--jumi-text-transform': 'none',
  '--jumi-top': 'auto',
  '--jumi-transform': transform,
  '--jumi-transform-origin': 'center',
  '--jumi-transform-origin-x': '50%',
  '--jumi-transform-origin-y': '50%',
  '--jumi-transform-origin-z': '0px',
  '--jumi-transform-style': 'flat',
  '--jumi-translate': translate,
  '--jumi-translate-3d': translate3d,
  '--jumi-translate-3x': '0',
  '--jumi-translate-3y': '0',
  '--jumi-translate-3z': '0',
  '--jumi-translate-sx': '0',
  '--jumi-translate-sy': '0',
  '--jumi-translate-x': 'translateX(0)',
  '--jumi-translate-y': 'translateY(0)',
  '--jumi-translate-z': 'translateZ(0)',
  '--jumi-width': 'auto',
  '--jumi-z-index': 'auto',
}

export const baseVariables = {
  ':root': variables,
}
