import {
  animationRange,
  animationRangeEnd,
  animationRangeStart,
} from '@/composition/animation-range'
import { animationTimelineInset } from '@/composition/animation-timeline'
import { aspectRatio } from '@/composition/aspect-ratio'
import { backdropFilter } from '@/composition/backdrop-filter'
import { display } from '@/composition/display'
import { filter } from '@/composition/filter'
import {
  matrix,
  matrix3d,
  rotate,
  rotate3d,
  scale,
  scale3d,
  skew,
  transform,
  translate,
  translate3d,
} from '@/composition/transform'

export const variables = {
  '--jumi-animation-composition': 'replace',
  '--jumi-animation-delay': '0s',
  '--jumi-animation-direction': 'alternate-reverse',
  '--jumi-animation-duration': '1s',
  '--jumi-animation-fill-mode': 'forwards',
  '--jumi-animation-iteration-count': '1',
  '--jumi-animation-name': 'none',
  '--jumi-animation-play-state': 'running',
  '--jumi-animation-range': animationRange,
  '--jumi-animation-range-end': animationRangeEnd,
  '--jumi-animation-range-end-length': '100%',
  '--jumi-animation-range-end-name': 'normal',
  '--jumi-animation-range-start': animationRangeStart,
  '--jumi-animation-range-start-length': '0%',
  '--jumi-animation-range-start-name': 'normal',
  '--jumi-animation-timeline': 'auto',
  '--jumi-animation-timeline-inset': animationTimelineInset,
  '--jumi-animation-timing-function': 'ease',
  '--jumi-aspect-ratio': aspectRatio,
  '--jumi-aspect-ratio-height': 'auto',
  '--jumi-aspect-ratio-width': 'auto',
  '--jumi-backdrop-blur': 'blur(0)',
  '--jumi-backdrop-brightness': 'brightness(1)',
  '--jumi-backdrop-contrast': 'contrast(1)',
  '--jumi-backdrop-filter': backdropFilter,
  '--jumi-backdrop-grayscale': 'grayscale(0)',
  '--jumi-backdrop-hue-rotate': 'hue-rotate(0deg)',
  '--jumi-backdrop-invert': 'invert(0)',
  '--jumi-backdrop-opacity': 'opacity(1)',
  '--jumi-backdrop-saturate': 'saturate(1)',
  '--jumi-backdrop-sepia': 'sepia(0)',
  '--jumi-background-color': 'transparent',
  '--jumi-background-position': '0% 0%',
  '--jumi-background-size': 'auto',
  '--jumi-blur': 'blur(0)',
  '--jumi-border-color': 'currentColor',
  '--jumi-border-radius': '0',
  '--jumi-border-width': '0',
  '--jumi-bottom': 'auto',
  '--jumi-brightness': 'brightness(1)',
  '--jumi-color': 'inherit',
  '--jumi-contrast': 'contrast(1)',
  '--jumi-display': display,
  '--jumi-display-inside': 'flow',
  '--jumi-display-ouside': 'block',
  '--jumi-drop-shadow': 'drop-shadow(0 0 0 transparent)',
  '--jumi-fill': 'currentColor',
  '--jumi-filter': filter,
  '--jumi-flex-basis': 'auto',
  '--jumi-flex-grow': '0',
  '--jumi-flex-shrink': '1',
  '--jumi-font-size': '1rem',
  '--jumi-font-weight': '400',
  '--jumi-gap': '0',
  '--jumi-grayscale': 'grayscale(0)',
  '--jumi-height': 'auto',
  '--jumi-hue-rotate': 'hue-rotate(0deg)',
  '--jumi-initial-letter': 'normal',
  '--jumi-invert': 'invert(0)',
  '--jumi-left': 'auto',
  '--jumi-letter-spacing': 'normal',
  '--jumi-line-height': 'normal',
  '--jumi-margin': '0',
  '--jumi-matrix': matrix,
  '--jumi-matrix-3d': matrix3d,
  '--jumi-opacity': '1',
  '--jumi-order': '0',
  '--jumi-outline-color': 'currentColor',
  '--jumi-outline-offset': '0',
  '--jumi-outline-width': '0',
  '--jumi-perspective': 'perspective(none)',
  '--jumi-perspective-origin': 'center',
  '--jumi-right': 'auto',
  '--jumi-rotate': rotate,
  '--jumi-rotate-3d': rotate3d,
  '--jumi-rotate-3x': '0',
  '--jumi-rotate-3y': '0',
  '--jumi-rotate-3z': '0',
  '--jumi-rotate-angle': '0deg',
  '--jumi-rotate-x': 'rotateX(0deg)',
  '--jumi-rotate-y': 'rotateY(0deg)',
  '--jumi-rotate-z': 'rotateZ(0deg)',
  '--jumi-saturate': 'saturate(1)',
  '--jumi-scale': scale,
  '--jumi-scale-3d': scale3d,
  '--jumi-scale-x': 'scaleX(1)',
  '--jumi-scale-y': 'scaleY(1)',
  '--jumi-scale-z': 'scaleZ(1)',
  '--jumi-sepia': 'sepia(0)',
  '--jumi-shadow': 'none',
  '--jumi-shadow-color': '0 0 0 0 transparent',
  '--jumi-shadow-offset-x': '0',
  '--jumi-shadow-offset-y': '0',
  '--jumi-shadow-opacity': '1',
  '--jumi-shadow-radius': '0',
  '--jumi-skew': skew,
  '--jumi-skew-x': 'skewX(0deg)',
  '--jumi-skew-y': 'skewY(0deg)',
  '--jumi-stroke': 'none',
  '--jumi-stroke-dasharray': 'none',
  '--jumi-stroke-dashoffset': '0',
  '--jumi-stroke-width': '1',
  '--jumi-text-align': 'baseline',
  '--jumi-text-shadow': 'none',
  '--jumi-top': 'auto',
  '--jumi-transform': transform,
  '--jumi-transform-origin': 'center',
  '--jumi-transform-origin-x': '50%',
  '--jumi-transform-origin-y': '50%',
  '--jumi-transform-origin-z': '0px',
  '--jumi-transform-style': 'flat',
  '--jumi-translate': translate,
  '--jumi-translate-3d': translate3d,
  '--jumi-translate-x': 'translateX(0)',
  '--jumi-translate-y': 'translateY(0)',
  '--jumi-translate-z': 'translateZ(0)',
  '--jumi-width': 'auto',
  '--jumi-z-index': 'auto',
}

export const baseVariables = {
  '.animate': variables,
}
