import type { Meta, StoryObj } from '@storybook/react-vite'

import { AnimationGrid } from './components'
import { families } from './effects.generated'

/**
 * The effects Jumi ships, grouped for the Storybook sidebar.
 *
 * Generated by `scripts/prepare-stories.mjs` from the `@keyframes jumi-*` names in
 * `src/keyframes/effects.ts`. Do not edit by hand — `pnpm stories:check` compares this file to the
 * registry and fails if they disagree.
 */

const meta: Meta = {
  parameters: { layout: 'fullscreen' },
  title: 'Animations',
}

export default meta
type Story = StoryObj

/**
 * One story per family, over the effects in that family. Nothing here decides what exists: a
 * family with no effects would be an empty grid, which the check upstream prevents.
 */
const familyStory = (family: string): Story => ({
  name: family,
  render: () => (
    <AnimationGrid
      animations={
        families.find(entry => entry.family === family)?.effects ?? []
      }
      title={family}
    />
  ),
})

export const Accordion: Story = familyStory('accordion')
export const Arc: Story = familyStory('arc')
export const Back: Story = familyStory('back')
export const Blink: Story = familyStory('blink')
export const Blur: Story = familyStory('blur')
export const Bounce: Story = familyStory('bounce')
export const Bubble: Story = familyStory('bubble')
export const Circle: Story = familyStory('circle')
export const Diamond: Story = familyStory('diamond')
export const Distort: Story = familyStory('distort')
export const Drip: Story = familyStory('drip')
export const Elastic: Story = familyStory('elastic')
export const Expand: Story = familyStory('expand')
export const Explode: Story = familyStory('explode')
export const Fade: Story = familyStory('fade')
export const Fall: Story = familyStory('fall')
export const Figure: Story = familyStory('figure')
export const Flicker: Story = familyStory('flicker')
export const Flip: Story = familyStory('flip')
export const Floating: Story = familyStory('floating')
export const Fold: Story = familyStory('fold')
export const Glitch: Story = familyStory('glitch')
export const Glow: Story = familyStory('glow')
export const Heart: Story = familyStory('heart')
export const Hue: Story = familyStory('hue')
export const Implode: Story = familyStory('implode')
export const Jello: Story = familyStory('jello')
export const Letter: Story = familyStory('letter')
export const Lift: Story = familyStory('lift')
export const Magnetic: Story = familyStory('magnetic')
export const Mask: Story = familyStory('mask')
export const Melt: Story = familyStory('melt')
export const Morph: Story = familyStory('morph')
export const Neon: Story = familyStory('neon')
export const Power: Story = familyStory('power')
export const Pulsing: Story = familyStory('pulsing')
export const Reveal: Story = familyStory('reveal')
export const Ripple: Story = familyStory('ripple')
export const Rotate: Story = familyStory('rotate')
export const Rush: Story = familyStory('rush')
export const Scatter: Story = familyStory('scatter')
export const Shadow: Story = familyStory('shadow')
export const Shake: Story = familyStory('shake')
export const Shimmer: Story = familyStory('shimmer')
export const Skew: Story = familyStory('skew')
export const Slide: Story = familyStory('slide')
export const Spinning: Story = familyStory('spinning')
export const Spiral: Story = familyStory('spiral')
export const Splash: Story = familyStory('splash')
export const Spring: Story = familyStory('spring')
export const Square: Story = familyStory('square')
export const Swing: Story = familyStory('swing')
export const Tada: Story = familyStory('tada')
export const Throw: Story = familyStory('throw')
export const Tilt: Story = familyStory('tilt')
export const Triangle: Story = familyStory('triangle')
export const Twist: Story = familyStory('twist')
export const Typing: Story = familyStory('typing')
export const Unfold: Story = familyStory('unfold')
export const Unmask: Story = familyStory('unmask')
export const Wave: Story = familyStory('wave')
export const Wiggle: Story = familyStory('wiggle')
export const Wobble: Story = familyStory('wobble')
export const Wobbling: Story = familyStory('wobbling')
export const Word: Story = familyStory('word')
export const Zoom: Story = familyStory('zoom')
