/**
 * The effects Jumi ships, grouped for the Storybook sidebar.
 *
 * Generated by `scripts/prepare-stories.mjs` from the `@keyframes jumi-*` names in
 * `src/keyframes/effects.ts`. Do not edit by hand — `pnpm stories:check` compares this file to the
 * registry and fails if they disagree.
 */

export interface Effect {
  /** The utility class without its `animate-` prefix, which `AnimationGrid` applies. */
  class: string
  /** The effect's name, which is also what its card is titled. */
  name: string
}

export interface Family {
  effects: Array<Effect>
  family: string
}

export const families: Array<Family> = [
  {
    effects: [
      {
        class: 'accordion',
        name: 'accordion',
      },
    ],
    family: 'accordion',
  },
  {
    effects: [
      {
        class: 'arc-bottom-left',
        name: 'arc-bottom-left',
      },
      {
        class: 'arc-bottom-right',
        name: 'arc-bottom-right',
      },
      {
        class: 'arc-top-left',
        name: 'arc-top-left',
      },
      {
        class: 'arc-top-right',
        name: 'arc-top-right',
      },
    ],
    family: 'arc',
  },
  {
    effects: [
      {
        class: 'back-in',
        name: 'back-in',
      },
      {
        class: 'back-in-down',
        name: 'back-in-down',
      },
      {
        class: 'back-in-left',
        name: 'back-in-left',
      },
      {
        class: 'back-in-right',
        name: 'back-in-right',
      },
      {
        class: 'back-in-up',
        name: 'back-in-up',
      },
    ],
    family: 'back',
  },
  {
    effects: [
      {
        class: 'blink',
        name: 'blink',
      },
    ],
    family: 'blink',
  },
  {
    effects: [
      {
        class: 'blur-in',
        name: 'blur-in',
      },
      {
        class: 'blur-out',
        name: 'blur-out',
      },
    ],
    family: 'blur',
  },
  {
    effects: [
      {
        class: 'bounce-in',
        name: 'bounce-in',
      },
      {
        class: 'bounce-in-down',
        name: 'bounce-in-down',
      },
      {
        class: 'bounce-in-left',
        name: 'bounce-in-left',
      },
      {
        class: 'bounce-in-right',
        name: 'bounce-in-right',
      },
      {
        class: 'bounce-in-up',
        name: 'bounce-in-up',
      },
      {
        class: 'bounce-out',
        name: 'bounce-out',
      },
      {
        class: 'bounce-out-down',
        name: 'bounce-out-down',
      },
      {
        class: 'bounce-out-left',
        name: 'bounce-out-left',
      },
      {
        class: 'bounce-out-right',
        name: 'bounce-out-right',
      },
      {
        class: 'bounce-out-up',
        name: 'bounce-out-up',
      },
    ],
    family: 'bounce',
  },
  {
    effects: [
      {
        class: 'bubble',
        name: 'bubble',
      },
    ],
    family: 'bubble',
  },
  {
    effects: [
      {
        class: 'circle-in',
        name: 'circle-in',
      },
      {
        class: 'circle-in-bottom-left',
        name: 'circle-in-bottom-left',
      },
      {
        class: 'circle-in-bottom-right',
        name: 'circle-in-bottom-right',
      },
      {
        class: 'circle-in-top-left',
        name: 'circle-in-top-left',
      },
      {
        class: 'circle-in-top-right',
        name: 'circle-in-top-right',
      },
      {
        class: 'circle-out',
        name: 'circle-out',
      },
      {
        class: 'circle-out-bottom-left',
        name: 'circle-out-bottom-left',
      },
      {
        class: 'circle-out-bottom-right',
        name: 'circle-out-bottom-right',
      },
      {
        class: 'circle-out-top-left',
        name: 'circle-out-top-left',
      },
      {
        class: 'circle-out-top-right',
        name: 'circle-out-top-right',
      },
    ],
    family: 'circle',
  },
  {
    effects: [
      {
        class: 'diamond-in',
        name: 'diamond-in',
      },
      {
        class: 'diamond-out',
        name: 'diamond-out',
      },
    ],
    family: 'diamond',
  },
  {
    effects: [
      {
        class: 'distort',
        name: 'distort',
      },
    ],
    family: 'distort',
  },
  {
    effects: [
      {
        class: 'drip',
        name: 'drip',
      },
    ],
    family: 'drip',
  },
  {
    effects: [
      {
        class: 'elastic',
        name: 'elastic',
      },
    ],
    family: 'elastic',
  },
  {
    effects: [
      {
        class: 'expand-down',
        name: 'expand-down',
      },
      {
        class: 'expand-left',
        name: 'expand-left',
      },
      {
        class: 'expand-right',
        name: 'expand-right',
      },
      {
        class: 'expand-up',
        name: 'expand-up',
      },
    ],
    family: 'expand',
  },
  {
    effects: [
      {
        class: 'explode',
        name: 'explode',
      },
    ],
    family: 'explode',
  },
  {
    effects: [
      {
        class: 'fade-in',
        name: 'fade-in',
      },
      {
        class: 'fade-in-down',
        name: 'fade-in-down',
      },
      {
        class: 'fade-in-left',
        name: 'fade-in-left',
      },
      {
        class: 'fade-in-right',
        name: 'fade-in-right',
      },
      {
        class: 'fade-in-up',
        name: 'fade-in-up',
      },
      {
        class: 'fade-out',
        name: 'fade-out',
      },
      {
        class: 'fade-out-down',
        name: 'fade-out-down',
      },
      {
        class: 'fade-out-left',
        name: 'fade-out-left',
      },
      {
        class: 'fade-out-right',
        name: 'fade-out-right',
      },
      {
        class: 'fade-out-up',
        name: 'fade-out-up',
      },
    ],
    family: 'fade',
  },
  {
    effects: [
      {
        class: 'fall-down',
        name: 'fall-down',
      },
      {
        class: 'fall-left',
        name: 'fall-left',
      },
      {
        class: 'fall-right',
        name: 'fall-right',
      },
      {
        class: 'fall-up',
        name: 'fall-up',
      },
    ],
    family: 'fall',
  },
  {
    effects: [
      {
        class: 'figure-eight',
        name: 'figure-eight',
      },
    ],
    family: 'figure',
  },
  {
    effects: [
      {
        class: 'flicker',
        name: 'flicker',
      },
    ],
    family: 'flicker',
  },
  {
    effects: [
      {
        class: 'flip-card-x',
        name: 'flip-card-x',
      },
      {
        class: 'flip-card-y',
        name: 'flip-card-y',
      },
      {
        class: 'flip-diagonal',
        name: 'flip-diagonal',
      },
      {
        class: 'flip-in-bottom',
        name: 'flip-in-bottom',
      },
      {
        class: 'flip-in-left',
        name: 'flip-in-left',
      },
      {
        class: 'flip-in-right',
        name: 'flip-in-right',
      },
      {
        class: 'flip-in-top',
        name: 'flip-in-top',
      },
      {
        class: 'flip-in-x',
        name: 'flip-in-x',
      },
      {
        class: 'flip-in-y',
        name: 'flip-in-y',
      },
      {
        class: 'flip-wobble-x',
        name: 'flip-wobble-x',
      },
      {
        class: 'flip-wobble-y',
        name: 'flip-wobble-y',
      },
      {
        class: 'flip-x',
        name: 'flip-x',
      },
      {
        class: 'flip-x-elastic',
        name: 'flip-x-elastic',
      },
      {
        class: 'flip-y',
        name: 'flip-y',
      },
      {
        class: 'flip-y-elastic',
        name: 'flip-y-elastic',
      },
      {
        class: 'flip-zoom-x',
        name: 'flip-zoom-x',
      },
      {
        class: 'flip-zoom-y',
        name: 'flip-zoom-y',
      },
    ],
    family: 'flip',
  },
  {
    effects: [
      {
        class: 'floating',
        name: 'floating',
      },
    ],
    family: 'floating',
  },
  {
    effects: [
      {
        class: 'fold-in',
        name: 'fold-in',
      },
      {
        class: 'fold-out',
        name: 'fold-out',
      },
    ],
    family: 'fold',
  },
  {
    effects: [
      {
        class: 'glitch',
        name: 'glitch',
      },
    ],
    family: 'glitch',
  },
  {
    effects: [
      {
        class: 'glow',
        name: 'glow',
      },
    ],
    family: 'glow',
  },
  {
    effects: [
      {
        class: 'heart-beat',
        name: 'heart-beat',
      },
    ],
    family: 'heart',
  },
  {
    effects: [
      {
        class: 'hue-shift',
        name: 'hue-shift',
      },
    ],
    family: 'hue',
  },
  {
    effects: [
      {
        class: 'implode',
        name: 'implode',
      },
    ],
    family: 'implode',
  },
  {
    effects: [
      {
        class: 'jello',
        name: 'jello',
      },
    ],
    family: 'jello',
  },
  {
    effects: [
      {
        class: 'letter-space-in',
        name: 'letter-space-in',
      },
      {
        class: 'letter-space-out',
        name: 'letter-space-out',
      },
    ],
    family: 'letter',
  },
  {
    effects: [
      {
        class: 'lift',
        name: 'lift',
      },
    ],
    family: 'lift',
  },
  {
    effects: [
      {
        class: 'magnetic',
        name: 'magnetic',
      },
    ],
    family: 'magnetic',
  },
  {
    effects: [
      {
        class: 'mask-bottom',
        name: 'mask-bottom',
      },
      {
        class: 'mask-bottom-left',
        name: 'mask-bottom-left',
      },
      {
        class: 'mask-bottom-right',
        name: 'mask-bottom-right',
      },
      {
        class: 'mask-center',
        name: 'mask-center',
      },
      {
        class: 'mask-left',
        name: 'mask-left',
      },
      {
        class: 'mask-right',
        name: 'mask-right',
      },
      {
        class: 'mask-top',
        name: 'mask-top',
      },
      {
        class: 'mask-top-left',
        name: 'mask-top-left',
      },
      {
        class: 'mask-top-right',
        name: 'mask-top-right',
      },
    ],
    family: 'mask',
  },
  {
    effects: [
      {
        class: 'melt',
        name: 'melt',
      },
    ],
    family: 'melt',
  },
  {
    effects: [
      {
        class: 'morph',
        name: 'morph',
      },
    ],
    family: 'morph',
  },
  {
    effects: [
      {
        class: 'neon',
        name: 'neon',
      },
    ],
    family: 'neon',
  },
  {
    effects: [
      {
        class: 'power-off',
        name: 'power-off',
      },
      {
        class: 'power-on',
        name: 'power-on',
      },
    ],
    family: 'power',
  },
  {
    effects: [
      {
        class: 'pulsing',
        name: 'pulsing',
      },
    ],
    family: 'pulsing',
  },
  {
    effects: [
      {
        class: 'reveal-down',
        name: 'reveal-down',
      },
      {
        class: 'reveal-left',
        name: 'reveal-left',
      },
      {
        class: 'reveal-right',
        name: 'reveal-right',
      },
      {
        class: 'reveal-swipe',
        name: 'reveal-swipe',
      },
      {
        class: 'reveal-up',
        name: 'reveal-up',
      },
    ],
    family: 'reveal',
  },
  {
    effects: [
      {
        class: 'ripple',
        name: 'ripple',
      },
    ],
    family: 'ripple',
  },
  {
    effects: [
      {
        class: 'rotate-left',
        name: 'rotate-left',
      },
      {
        class: 'rotate-right',
        name: 'rotate-right',
      },
    ],
    family: 'rotate',
  },
  {
    effects: [
      {
        class: 'rush-in-down',
        name: 'rush-in-down',
      },
      {
        class: 'rush-in-left',
        name: 'rush-in-left',
      },
      {
        class: 'rush-in-right',
        name: 'rush-in-right',
      },
      {
        class: 'rush-in-up',
        name: 'rush-in-up',
      },
      {
        class: 'rush-out-down',
        name: 'rush-out-down',
      },
      {
        class: 'rush-out-left',
        name: 'rush-out-left',
      },
      {
        class: 'rush-out-right',
        name: 'rush-out-right',
      },
      {
        class: 'rush-out-up',
        name: 'rush-out-up',
      },
    ],
    family: 'rush',
  },
  {
    effects: [
      {
        class: 'scatter',
        name: 'scatter',
      },
    ],
    family: 'scatter',
  },
  {
    effects: [
      {
        class: 'shadow',
        name: 'shadow',
      },
    ],
    family: 'shadow',
  },
  {
    effects: [
      {
        class: 'shake',
        name: 'shake',
      },
    ],
    family: 'shake',
  },
  {
    effects: [
      {
        class: 'shimmer',
        name: 'shimmer',
      },
    ],
    family: 'shimmer',
  },
  {
    effects: [
      {
        class: 'skew-down',
        name: 'skew-down',
      },
      {
        class: 'skew-in',
        name: 'skew-in',
      },
      {
        class: 'skew-left',
        name: 'skew-left',
      },
      {
        class: 'skew-left-down',
        name: 'skew-left-down',
      },
      {
        class: 'skew-left-up',
        name: 'skew-left-up',
      },
      {
        class: 'skew-out',
        name: 'skew-out',
      },
      {
        class: 'skew-right',
        name: 'skew-right',
      },
      {
        class: 'skew-right-down',
        name: 'skew-right-down',
      },
      {
        class: 'skew-right-up',
        name: 'skew-right-up',
      },
      {
        class: 'skew-up',
        name: 'skew-up',
      },
    ],
    family: 'skew',
  },
  {
    effects: [
      {
        class: 'slide-in-down',
        name: 'slide-in-down',
      },
      {
        class: 'slide-in-down-elastic',
        name: 'slide-in-down-elastic',
      },
      {
        class: 'slide-in-left',
        name: 'slide-in-left',
      },
      {
        class: 'slide-in-right',
        name: 'slide-in-right',
      },
      {
        class: 'slide-in-up',
        name: 'slide-in-up',
      },
      {
        class: 'slide-in-up-elastic',
        name: 'slide-in-up-elastic',
      },
      {
        class: 'slide-in-up-left',
        name: 'slide-in-up-left',
      },
      {
        class: 'slide-in-up-right',
        name: 'slide-in-up-right',
      },
      {
        class: 'slide-out-down',
        name: 'slide-out-down',
      },
      {
        class: 'slide-out-left',
        name: 'slide-out-left',
      },
      {
        class: 'slide-out-right',
        name: 'slide-out-right',
      },
      {
        class: 'slide-out-up',
        name: 'slide-out-up',
      },
      {
        class: 'slide-peek-down',
        name: 'slide-peek-down',
      },
      {
        class: 'slide-peek-left',
        name: 'slide-peek-left',
      },
      {
        class: 'slide-peek-right',
        name: 'slide-peek-right',
      },
      {
        class: 'slide-peek-up',
        name: 'slide-peek-up',
      },
      {
        class: 'slide-stack',
        name: 'slide-stack',
      },
    ],
    family: 'slide',
  },
  {
    effects: [
      {
        class: 'spinning',
        name: 'spinning',
      },
    ],
    family: 'spinning',
  },
  {
    effects: [
      {
        class: 'spiral',
        name: 'spiral',
      },
      {
        class: 'spiral-back-in',
        name: 'spiral-back-in',
      },
      {
        class: 'spiral-back-out',
        name: 'spiral-back-out',
      },
      {
        class: 'spiral-in',
        name: 'spiral-in',
      },
      {
        class: 'spiral-out',
        name: 'spiral-out',
      },
      {
        class: 'spiral-path',
        name: 'spiral-path',
      },
    ],
    family: 'spiral',
  },
  {
    effects: [
      {
        class: 'splash',
        name: 'splash',
      },
    ],
    family: 'splash',
  },
  {
    effects: [
      {
        class: 'spring-down',
        name: 'spring-down',
      },
      {
        class: 'spring-left',
        name: 'spring-left',
      },
      {
        class: 'spring-right',
        name: 'spring-right',
      },
      {
        class: 'spring-up',
        name: 'spring-up',
      },
    ],
    family: 'spring',
  },
  {
    effects: [
      {
        class: 'square-in',
        name: 'square-in',
      },
      {
        class: 'square-in-bottom-left',
        name: 'square-in-bottom-left',
      },
      {
        class: 'square-in-bottom-right',
        name: 'square-in-bottom-right',
      },
      {
        class: 'square-in-top-left',
        name: 'square-in-top-left',
      },
      {
        class: 'square-in-top-right',
        name: 'square-in-top-right',
      },
      {
        class: 'square-out',
        name: 'square-out',
      },
      {
        class: 'square-out-bottom-left',
        name: 'square-out-bottom-left',
      },
      {
        class: 'square-out-bottom-right',
        name: 'square-out-bottom-right',
      },
      {
        class: 'square-out-top-left',
        name: 'square-out-top-left',
      },
      {
        class: 'square-out-top-right',
        name: 'square-out-top-right',
      },
    ],
    family: 'square',
  },
  {
    effects: [
      {
        class: 'swing',
        name: 'swing',
      },
    ],
    family: 'swing',
  },
  {
    effects: [
      {
        class: 'tada',
        name: 'tada',
      },
    ],
    family: 'tada',
  },
  {
    effects: [
      {
        class: 'throw-down',
        name: 'throw-down',
      },
      {
        class: 'throw-left',
        name: 'throw-left',
      },
      {
        class: 'throw-right',
        name: 'throw-right',
      },
      {
        class: 'throw-up',
        name: 'throw-up',
      },
    ],
    family: 'throw',
  },
  {
    effects: [
      {
        class: 'tilt',
        name: 'tilt',
      },
    ],
    family: 'tilt',
  },
  {
    effects: [
      {
        class: 'triangle-in',
        name: 'triangle-in',
      },
      {
        class: 'triangle-in-bottom-left',
        name: 'triangle-in-bottom-left',
      },
      {
        class: 'triangle-in-bottom-right',
        name: 'triangle-in-bottom-right',
      },
      {
        class: 'triangle-in-top-left',
        name: 'triangle-in-top-left',
      },
      {
        class: 'triangle-in-top-right',
        name: 'triangle-in-top-right',
      },
      {
        class: 'triangle-out',
        name: 'triangle-out',
      },
      {
        class: 'triangle-out-bottom-left',
        name: 'triangle-out-bottom-left',
      },
      {
        class: 'triangle-out-bottom-right',
        name: 'triangle-out-bottom-right',
      },
      {
        class: 'triangle-out-top-left',
        name: 'triangle-out-top-left',
      },
      {
        class: 'triangle-out-top-right',
        name: 'triangle-out-top-right',
      },
    ],
    family: 'triangle',
  },
  {
    effects: [
      {
        class: 'twist',
        name: 'twist',
      },
      {
        class: 'twist-in',
        name: 'twist-in',
      },
      {
        class: 'twist-out',
        name: 'twist-out',
      },
    ],
    family: 'twist',
  },
  {
    effects: [
      {
        class: 'typing',
        name: 'typing',
      },
    ],
    family: 'typing',
  },
  {
    effects: [
      {
        class: 'unfold-x',
        name: 'unfold-x',
      },
      {
        class: 'unfold-y',
        name: 'unfold-y',
      },
    ],
    family: 'unfold',
  },
  {
    effects: [
      {
        class: 'unmask',
        name: 'unmask',
      },
      {
        class: 'unmask-bottom',
        name: 'unmask-bottom',
      },
      {
        class: 'unmask-bottom-left',
        name: 'unmask-bottom-left',
      },
      {
        class: 'unmask-bottom-right',
        name: 'unmask-bottom-right',
      },
      {
        class: 'unmask-left',
        name: 'unmask-left',
      },
      {
        class: 'unmask-right',
        name: 'unmask-right',
      },
      {
        class: 'unmask-top',
        name: 'unmask-top',
      },
      {
        class: 'unmask-top-left',
        name: 'unmask-top-left',
      },
      {
        class: 'unmask-top-right',
        name: 'unmask-top-right',
      },
    ],
    family: 'unmask',
  },
  {
    effects: [
      {
        class: 'wave',
        name: 'wave',
      },
    ],
    family: 'wave',
  },
  {
    effects: [
      {
        class: 'wiggle',
        name: 'wiggle',
      },
    ],
    family: 'wiggle',
  },
  {
    effects: [
      {
        class: 'wobble',
        name: 'wobble',
      },
    ],
    family: 'wobble',
  },
  {
    effects: [
      {
        class: 'wobbling',
        name: 'wobbling',
      },
    ],
    family: 'wobbling',
  },
  {
    effects: [
      {
        class: 'word-slide',
        name: 'word-slide',
      },
    ],
    family: 'word',
  },
  {
    effects: [
      {
        class: 'zoom-in',
        name: 'zoom-in',
      },
      {
        class: 'zoom-in-down',
        name: 'zoom-in-down',
      },
      {
        class: 'zoom-in-elastic',
        name: 'zoom-in-elastic',
      },
      {
        class: 'zoom-in-left',
        name: 'zoom-in-left',
      },
      {
        class: 'zoom-in-right',
        name: 'zoom-in-right',
      },
      {
        class: 'zoom-in-up',
        name: 'zoom-in-up',
      },
      {
        class: 'zoom-out',
        name: 'zoom-out',
      },
      {
        class: 'zoom-out-down',
        name: 'zoom-out-down',
      },
      {
        class: 'zoom-out-elastic',
        name: 'zoom-out-elastic',
      },
      {
        class: 'zoom-out-left',
        name: 'zoom-out-left',
      },
      {
        class: 'zoom-out-right',
        name: 'zoom-out-right',
      },
      {
        class: 'zoom-out-up',
        name: 'zoom-out-up',
      },
      {
        class: 'zoom-pulse',
        name: 'zoom-pulse',
      },
      {
        class: 'zoom-pulse-grow',
        name: 'zoom-pulse-grow',
      },
      {
        class: 'zoom-pulse-shrink',
        name: 'zoom-pulse-shrink',
      },
      {
        class: 'zoom-tilt-in',
        name: 'zoom-tilt-in',
      },
      {
        class: 'zoom-tilt-out',
        name: 'zoom-tilt-out',
      },
    ],
    family: 'zoom',
  },
]
