export const CRAWLERS = [
  "360spider",
  "adsbot-google",
  "apis-google",
  "ahrefsbot",
  "baiduspider",
  "bingbot",
  "bingpreview",
  "bytespider",
  "coccocbot",
  "duplexweb-google",
  "facebookexternal",
  "facebookexternalhit",
  "feedfetcher-google",
  "google favicon",
  "google web preview",
  "google-read-aloud",
  "googlebot",
  "googleweblight",
  "linespider",
  "mediapartners-google",
  "petalbot",
  "pinterest",
  "screaming frog",
  "sogou web spider",
  "sogou inst spider",
  "storebot-google",
  "qwantify",
  "yahoo! slurp",
  "yandexbot",
  "yeti",
  "yisouspider",
];
