#!/usr/bin/env node
/**
 * Generate the Storybook's effect catalog from the effects Jumi actually ships.
 *
 * The stories used to be hand-written, one file per effect family, and they drifted: of the 265
 * distinct effect classes they referenced, 187 named effects that have never existed — a family
 * structure (`arc-in-gentle`, `circle-in-center`, `spiral-in-galaxy`, `reveal-in-blinds`) that was
 * imagined rather than measured, plus near-misses of real names (`pulse` for `pulsing`, `float` for
 * `floating`). Nothing failed, because the Storybook is not built by `pnpm check` and an unknown
 * `animate-*` class is silently ignored by Tailwind — a demo that animates nothing looks exactly
 * like a demo whose effect is subtle.
 *
 * So the catalog is derived rather than written. `src/keyframes/effects.ts` is the registry — the
 * same source `scripts/prepare-docs.mjs` reads for `docs/src/data/effects.json` — and the grouping
 * below is the only judgement in the file: an effect's family is its first segment, so `fade-in-up`
 * is a `fade`. That is a sidebar label, not a claim about the effect.
 *
 * `pnpm stories:check` asserts the generated files and the registry agree, so this only has to run
 * when the effects change.
 *
 * Run: pnpm stories:prepare
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'

import * as prettier from 'prettier'

const root = new URL('../', import.meta.url)

const registry = await readFile(
  new URL('src/keyframes/effects.ts', root),
  'utf8',
)
const names = [...registry.matchAll(/'@keyframes jumi-([^']+)'/g)].map(
  match => match[1],
)

if (!names.length) {
  console.error(
    '✗ no effects found in src/keyframes/effects.ts — the extraction has gone stale',
  )
  process.exit(1)
}

/** The sidebar label an effect files under: its first segment. */
const familyOf = name => name.split('-')[0]

const grouped = new Map()

for (const name of names) {
  const family = familyOf(name)
  grouped.set(family, [...(grouped.get(family) ?? []), name])
}

const families = [...grouped]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([family, effects]) => ({ effects: [...effects].sort(), family }))

const banner = `/**
 * The effects Jumi ships, grouped for the Storybook sidebar.
 *
 * Generated by \`scripts/prepare-stories.mjs\` from the \`@keyframes jumi-*\` names in
 * \`src/keyframes/effects.ts\`. Do not edit by hand — \`pnpm stories:check\` compares this file to the
 * registry and fails if they disagree.
 */`

const data = `${banner}

export interface Effect {
  /** The utility class without its \`animate-\` prefix, which \`AnimationGrid\` applies. */
  class: string
  /** The effect's name, which is also what its card is titled. */
  name: string
}

export interface Family {
  effects: Array<Effect>
  family: string
}

export const families: Array<Family> = ${JSON.stringify(
  families.map(({ effects, family }) => ({
    effects: effects.map(name => ({ class: name, name })),
    family,
  })),
  null,
  2,
)}
`

/** `fade` → `Fade`, for a story export's identifier. */
const identifier = family => family[0].toUpperCase() + family.slice(1)

const exports = families
  .map(({ family }) => {
    const label = identifier(family)

    return `export const ${label}: Story = familyStory('${family}')`
  })
  .join('\n')

const stories = `import type { Meta, StoryObj } from '@storybook/react-vite'

import { AnimationGrid } from './components'
import { families } from './effects.generated'

${banner}

const meta: Meta = {
  parameters: { layout: 'fullscreen' },
  title: 'Animations',
}

export default meta
type Story = StoryObj

/**
 * One story per family, over the effects in that family. Nothing here decides what exists: a
 * family with no effects would be an empty grid, which the check upstream prevents.
 */
const familyStory = (family: string): Story => ({
  name: family,
  render: () => (
    <AnimationGrid
      animations={families.find(entry => entry.family === family)?.effects ?? []}
      title={family}
    />
  ),
})

${exports}
`

const prettierOptions = await prettier.resolveConfig(
  new URL('stories/animations/effects.generated.ts', root).pathname,
)

/**
 * Written the way the formatter writes it. A generated artifact the formatter disagrees with is a
 * diff on every `pnpm lint`, and the file it would keep rewriting is the one `stories-check.mjs`
 * reads as text — that check went red the first time the catalog was reformatted, because the
 * generated keys were double-quoted and the extraction looked for exactly that.
 */
const format = (source, filepath) =>
  prettier.format(source, { ...prettierOptions, filepath })

await mkdir(new URL('stories/animations/', root), { recursive: true })
await writeFile(
  new URL('stories/animations/effects.generated.ts', root),
  await format(data, 'stories/animations/effects.generated.ts'),
)
await writeFile(
  new URL('stories/animations/catalog.stories.tsx', root),
  await format(stories, 'stories/animations/catalog.stories.tsx'),
)

console.log(
  `Prepared ${names.length} effects in ${families.length} families for Storybook.`,
)
