import type { Collection, GetMatchUtilities, MatchUtilitiesPropertyValue, TailwindPropertyType, TailwindTheme } from '@/types'

import { join } from '@/helpers/join'

type TailwindSpec = {
  supportsNegativeValues?: boolean
  theme?: TailwindTheme
  values?: Collection<string>
  variable: string | string[]

}
export const getMatchTailwindUtilities: GetMatchUtilities = (creator) => {
  const rest = ({ supportsNegativeValues = false, theme, values = {}, variable }: TailwindSpec): MatchUtilitiesPropertyValue => {
    const variables = (stored: string) =>
      Array.isArray(variable)
        ? Object.fromEntries(variable.map(name => [name, stored]))
        : { [variable]: stored }

    return {
      fn: (value, { modifier }) => variables(modifier ? join([value, modifier]) : value),
      supportsNegativeValues,
      values: theme ? creator.theme(theme) : values,
    }
  }

  const tailwind: Partial<Record<TailwindPropertyType, MatchUtilitiesPropertyValue>> = {
    'accent': rest({ theme: 'accentColor', variable: '--jumi-accent-color' }),
    'aspect': rest({ theme: 'aspectRatio', variable: '--jumi-aspect-ratio' }),
    'backdrop-blur': rest({ theme: 'backdropBlur', variable: '--jumi-backdrop-filter-blur' }),
    'backdrop-brightness': rest({ theme: 'backdropBrightness', variable: '--jumi-backdrop-filter-brightness' }),
    'backdrop-contrast': rest({ theme: 'backdropContrast', variable: '--jumi-backdrop-filter-contrast' }),
    'backdrop-grayscale': rest({ theme: 'backdropGrayscale', variable: '--jumi-backdrop-filter-grayscale' }),
    'backdrop-hue-rotate': rest({ theme: 'backdropHueRotate', variable: '--jumi-backdrop-filter-hue-rotate' }),
    'backdrop-invert': rest({ theme: 'backdropInvert', variable: '--jumi-backdrop-filter-invert' }),
    'backdrop-opacity': rest({ theme: 'backdropOpacity', variable: '--jumi-backdrop-filter-opacity' }),
    'backdrop-saturate': rest({ theme: 'backdropSaturate', variable: '--jumi-backdrop-filter-saturate' }),
    'backdrop-sepia': rest({ theme: 'backdropSepia', variable: '--jumi-backdrop-filter-sepia' }),
    'basis': rest({ theme: 'flexBasis', variable: '--jumi-flex-basis' }),
    'bg': rest({ theme: 'backgroundColor', variable: '--jumi-background-color' }),
    'blur': rest({ theme: 'blur', variable: '--jumi-filter-blur' }),
    'border': rest({ theme: 'borderColor', variable: '--jumi-border-color' }),
    'border-spacing': rest({ theme: 'borderSpacing', variable: '--jumi-border-spacing' }),
    'border-spacing-x': rest({ theme: 'borderSpacing', variable: '--jumi-border-spacing-x' }),
    'border-spacing-y': rest({ theme: 'borderSpacing', variable: '--jumi-border-spacing-y' }),
    'bottom': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-bottom' }),
    'brightness': rest({ theme: 'brightness', variable: '--jumi-filter-brightness' }),
    'caret': rest({ theme: 'caretColor', variable: '--jumi-caret-color' }),
    'columns': rest({ theme: 'columns', variable: '--jumi-columns' }),
    'contain': rest({ variable: '--jumi-contain' }),
    'content': rest({ theme: 'content', variable: '--jumi-content' }),
    'contrast': rest({ theme: 'contrast', variable: '--jumi-filter-contrast' }),
    'cursor': rest({ theme: 'cursor', variable: '--jumi-cursor' }),
    'decoration': rest({ theme: 'textDecorationColor', variable: '--jumi-text-decoration-color' }),
    'drop-shadow': rest({ theme: 'dropShadow', variable: '--jumi-filter-drop-shadow' }),
    'fill': rest({ variable: '--jumi-fill' }),
    'gap': rest({ theme: 'gap', variable: '--jumi-gap' }),
    'gap-x': rest({ theme: 'gap', variable: '--jumi-column-gap' }),
    'gap-y': rest({ theme: 'gap', variable: '--jumi-row-gap' }),
    'grayscale': rest({ theme: 'grayscale', variable: '--jumi-filter-grayscale' }),
    'grow': rest({ theme: 'flexGrow', variable: '--jumi-flex-grow' }),
    'h': rest({ theme: 'height', variable: '--jumi-height' }),
    'hue-rotate': rest({ theme: 'hueRotate', variable: '--jumi-filter-hue-rotate' }),
    'indent': rest({ supportsNegativeValues: true, theme: 'textIndent', variable: '--jumi-text-indent' }),
    'inset': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset' }),
    'inset-be': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-block-end' }),
    'inset-bs': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-block-start' }),
    'inset-e': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-inline-end' }),
    'inset-s': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-inline-start' }),
    'inset-x': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-inline' }),
    'inset-y': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-inset-block' }),
    'invert': rest({ theme: 'invert', variable: '--jumi-filter-invert' }),
    'left': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-left' }),
    'm': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin' }),
    'max-h': rest({ theme: 'maxHeight', variable: '--jumi-max-height' }),
    'max-w': rest({ theme: 'maxWidth', variable: '--jumi-max-width' }),
    'mb': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-bottom' }),
    'mbe': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-block-end' }),
    'mbs': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-block-start' }),
    'me': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-inline-end' }),
    'min-h': rest({ theme: 'minHeight', variable: '--jumi-min-height' }),
    'min-w': rest({ theme: 'minWidth', variable: '--jumi-min-width' }),
    'ml': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-left' }),
    'mr': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-right' }),
    'ms': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-inline-start' }),
    'mt': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-top' }),
    'mx': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-inline' }),
    'my': rest({ supportsNegativeValues: true, theme: 'margin', variable: '--jumi-margin-block' }),
    'opacity': rest({ theme: 'opacity', variable: '--jumi-opacity' }),
    'order': rest({ theme: 'order', variable: '--jumi-order' }),
    'origin': rest({ theme: 'transformOrigin', variable: '--jumi-transform-origin' }),
    'outline': rest({ theme: 'outlineColor', variable: '--jumi-outline-color' }),
    'outline-offset': rest({ theme: 'outlineOffset', variable: '--jumi-outline-offset' }),
    'p': rest({ theme: 'padding', variable: '--jumi-padding' }),
    'pb': rest({ theme: 'padding', variable: '--jumi-padding-bottom' }),
    'pbe': rest({ theme: 'padding', variable: '--jumi-padding-block-end' }),
    'pbs': rest({ theme: 'padding', variable: '--jumi-padding-block-start' }),
    'pe': rest({ theme: 'padding', variable: '--jumi-padding-inline-end' }),
    'perspective': rest({ theme: 'perspective', variable: '--jumi-perspective' }),
    'perspective-origin': rest({ theme: 'transformOrigin', variable: '--jumi-perspective-origin' }),
    'pl': rest({ theme: 'padding', variable: '--jumi-padding-left' }),
    'pr': rest({ theme: 'padding', variable: '--jumi-padding-right' }),
    'ps': rest({ theme: 'padding', variable: '--jumi-padding-inline-start' }),
    'pt': rest({ theme: 'padding', variable: '--jumi-padding-top' }),
    'px': rest({ theme: 'padding', variable: '--jumi-padding-inline' }),
    'py': rest({ theme: 'padding', variable: '--jumi-padding-block' }),
    'right': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-right' }),
    'rotate': rest({ supportsNegativeValues: true, theme: 'rotate', variable: '--jumi-rotate' }),
    'rotate-x': rest({ supportsNegativeValues: true, theme: 'rotate', variable: '--jumi-rotate-x' }),
    'rotate-y': rest({ supportsNegativeValues: true, theme: 'rotate', variable: '--jumi-rotate-y' }),
    'rotate-z': rest({ supportsNegativeValues: true, theme: 'rotate', variable: '--jumi-rotate-z' }),
    'saturate': rest({ theme: 'saturate', variable: '--jumi-filter-saturate' }),
    'scale': rest({ supportsNegativeValues: true, theme: 'scale', variable: '--jumi-scale' }),
    'scale-x': rest({ supportsNegativeValues: true, theme: 'scale', variable: '--jumi-scale-x' }),
    'scale-y': rest({ supportsNegativeValues: true, theme: 'scale', variable: '--jumi-scale-y' }),
    'scale-z': rest({ supportsNegativeValues: true, theme: 'scale', variable: '--jumi-scale-z' }),
    'scroll-m': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin' }),
    'scroll-mb': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-bottom' }),
    'scroll-mbe': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-block-end' }),
    'scroll-mbs': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-block-start' }),
    'scroll-me': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-inline-end' }),
    'scroll-ml': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-left' }),
    'scroll-mr': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-right' }),
    'scroll-ms': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-inline-start' }),
    'scroll-mt': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-top' }),
    'scroll-mx': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-inline' }),
    'scroll-my': rest({ supportsNegativeValues: true, theme: 'scrollMargin', variable: '--jumi-scroll-margin-block' }),
    'scroll-p': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding' }),
    'scroll-pb': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-bottom' }),
    'scroll-pbe': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-block-end' }),
    'scroll-pbs': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-block-start' }),
    'scroll-pe': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-inline-end' }),
    'scroll-pl': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-left' }),
    'scroll-pr': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-right' }),
    'scroll-ps': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-inline-start' }),
    'scroll-pt': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-top' }),
    'scroll-px': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-inline' }),
    'scroll-py': rest({ theme: 'scrollPadding', variable: '--jumi-scroll-padding-block' }),
    'sepia': rest({ theme: 'sepia', variable: '--jumi-filter-sepia' }),
    'shadow': rest({ theme: 'boxShadow', variable: '--jumi-box-shadow' }),
    'shrink': rest({ theme: 'flexShrink', variable: '--jumi-flex-shrink' }),
    'size': rest({ theme: 'width', variable: ['--jumi-width', '--jumi-height'] }),
    'skew': rest({ supportsNegativeValues: true, theme: 'skew', variable: '--jumi-skew' }),
    'skew-x': rest({ supportsNegativeValues: true, theme: 'skew', variable: '--jumi-skew-x' }),
    'skew-y': rest({ supportsNegativeValues: true, theme: 'skew', variable: '--jumi-skew-y' }),
    'stroke': rest({ variable: '--jumi-stroke' }),
    'text': rest({ theme: 'textColor', variable: '--jumi-color' }),
    'text-shadow': rest({ theme: 'textShadow', variable: '--jumi-text-shadow' }),
    'top': rest({ supportsNegativeValues: true, theme: 'inset', variable: '--jumi-top' }),
    'tracking': rest({ theme: 'letterSpacing', variable: '--jumi-letter-spacing' }),
    'translate': rest({ supportsNegativeValues: true, theme: 'translate', variable: '--jumi-translate' }),
    'translate-x': rest({ supportsNegativeValues: true, theme: 'translate', variable: '--jumi-translate-x' }),
    'translate-y': rest({ supportsNegativeValues: true, theme: 'translate', variable: '--jumi-translate-y' }),
    'translate-z': rest({ supportsNegativeValues: true, theme: 'translate', variable: '--jumi-translate-z' }),
    'underline-offset': rest({ theme: 'textUnderlineOffset', variable: '--jumi-text-underline-offset' }),
    'w': rest({ theme: 'width', variable: '--jumi-width' }),
    'will-change': rest({ theme: 'willChange', variable: '--jumi-will-change' }),
    'z': rest({ theme: 'zIndex', variable: '--jumi-z-index' }),
    'zoom': rest({ variable: '--jumi-zoom' }),
  }

  return tailwind
}
