import type { PropertiesHyphen } from 'csstype'

import type { AnimationName } from '@/theme/animation-name'

export type AddProperty = {
  [K in AddPropertyKeys as `.${K}`]?: CssInJs
}

export type AddPropertyKeys = 'animate'

export type AnimationKeyframes = {
  [K in AnimationName as `@keyframes ${K}`]?: Keyframes
}

export type CssInJs = {
  [key: string]: CssInJs | CssInJs[] | string | string[]
}

export type CSSRuleObject = CssInJs | CssInJs[]

export type DataType
  = | 'absolute-size'
    | 'angle'
    | 'any'
    | 'bg-size'
    | 'color'
    | 'family-name'
    | 'generic-name'
    | 'image'
    | 'integer'
    | 'length'
    | 'line-width'
    | 'number'
    | 'percentage'
    | 'position'
    | 'ratio'
    | 'relative-size'
    | 'url'
    | 'vector'

export type KeyframeDefinition = Record<string, Record<string, any>>

export type Keyframes = Record<string, PropertiesHyphen>

export type MatchProperty = {
  [K in MatchPropertyKeys]: MatchPropertyValue
}

export type MatchPropertyKeys = 'animate' | `animate-${Property}` | `animate-${RevealAnimation}`
export interface MatchPropertyValue extends Partial<Options> {
  key?: TailwindTheme
  property: (value: string) => CSSRuleObject
}

export interface Options {
  modifiers: 'any' | Record<string, string>
  supportsNegativeValues: boolean
  type: DataType | DataType[]
  values: Record<string, string>
}

export type Property
  = | 'accent-color'
    | 'align-content'
    | 'align-items'
    | 'align-self'
    | 'alignment-baseline'
    | 'all'
    | 'anchor-name'
    | 'appearance'
    | 'aspect-ratio'
    | 'aspect-ratio-height'
    | 'aspect-ratio-width'
    | 'backdrop-blur'
    | 'backdrop-brightness'
    | 'backdrop-contrast'
    | 'backdrop-filter'
    | 'backdrop-grayscale'
    | 'backdrop-hue-rotate'
    | 'backdrop-invert'
    | 'backdrop-opacity'
    | 'backdrop-saturate'
    | 'backdrop-sepia'
    | 'backdrop-url'
    | 'backface-visibility'
    | 'background'
    | 'background-attachment'
    | 'background-blend-mode'
    | 'background-clip'
    | 'background-color'
    | 'background-image'
    | 'background-origin'
    | 'background-position'
    | 'background-position-x'
    | 'background-position-x-edge'
    | 'background-position-x-offset'
    | 'background-position-y'
    | 'background-position-y-edge'
    | 'background-position-y-offset'
    | 'background-repeat'
    | 'background-repeat-x'
    | 'background-repeat-y'
    | 'background-size'
    | 'background-size-height'
    | 'background-size-width'
    | 'block-size'
    | 'border'
    | 'border-block'
    | 'border-block-color'
    | 'border-block-end-color' // bottom
    | 'border-block-end-radius' // bottom
    | 'border-block-end-style' // bottom
    | 'border-block-end-width' // bottom
    | 'border-block-start-color' // top
    | 'border-block-start-radius' // top
    | 'border-block-start-style' // top
    | 'border-block-start-width' // top
    | 'border-block-style' // top-bottom
    | 'border-block-width' // top-bottom
    | 'border-bottom'
    | 'border-bottom-color'
    | 'border-bottom-left-radius'
    | 'border-bottom-radius'
    | 'border-bottom-right-radius'
    | 'border-bottom-style'
    | 'border-bottom-width'
    | 'border-bottom-width'
    | 'border-collapse'
    | 'border-color'
    | 'border-end-end-radius' // bottom-right
    | 'border-end-start-radius' // bottom-left
    | 'border-image'
    | 'border-image-outset'
    | 'border-image-outset-bottom'
    | 'border-image-outset-left'
    | 'border-image-outset-right'
    | 'border-image-outset-top'
    | 'border-image-outset-x'
    | 'border-image-outset-y'
    | 'border-image-repeat'
    | 'border-image-repeat-x'
    | 'border-image-repeat-y'
    | 'border-image-slice'
    | 'border-image-source'
    | 'border-image-width'
    | 'border-inline-end-radius' // right
    | 'border-inline-end-width' // right
    | 'border-inline-start-radius' // left
    | 'border-inline-start-width' // left
    | 'border-inline-width' // left-right
    | 'border-left-radius'
    | 'border-left-width'
    | 'border-radius'
    | 'border-right-radius'
    | 'border-right-width'
    | 'border-start-end-radius' // top-right
    | 'border-start-start-radius' // top-left
    | 'border-style'
    | 'border-top-left-radius'
    | 'border-top-radius'
    | 'border-top-right-radius'
    | 'border-top-width'
    | 'border-width'
    | 'bottom'
    | 'box-shadow'
    | 'box-shadow-blur'
    | 'box-shadow-color'
    | 'box-shadow-inset'
    | 'box-shadow-offset-x'
    | 'box-shadow-offset-y'
    | 'box-shadow-spread'
    | 'caret-color'
    | 'color'
    | 'column-count'
    | 'column-gap'
    | 'column-gap'
    | 'column-width'
    | 'columns'
    | 'composition'
    | 'cursor'
    | 'delay'
    | 'direction'
    | 'display'
    | 'drop-shadow'
    | 'duration'
    | 'fill'
    | 'fill-mode'
    | 'filter'
    | 'filter-blur'
    | 'filter-brightness'
    | 'filter-contrast'
    | 'filter-contrast'
    | 'filter-grayscale'
    | 'filter-hue-rotate'
    | 'filter-invert'
    | 'filter-opacity'
    | 'filter-saturate'
    | 'filter-sepia'
    | 'filter-url'
    | 'flex'
    | 'flex-basis'
    | 'flex-direction'
    | 'flex-flow'
    | 'flex-grow'
    | 'flex-shrink'
    | 'flex-wrap'
    | 'font-family'
    | 'font-size'
    | 'font-smoothing'
    | 'font-style'
    | 'font-variant-numeric'
    | 'font-weight'
    | 'gap'
    | 'grid-auto-columns'
    | 'grid-auto-flow'
    | 'grid-auto-rows'
    | 'grid-column'
    | 'grid-column-end'
    | 'grid-column-start'
    | 'grid-row'
    | 'grid-row-end'
    | 'grid-row-start'
    | 'grid-template-columns'
    | 'grid-template-rows'
    | 'height'
    | 'inset'
    | 'inset-block'
    | 'inset-block-end'
    | 'inset-block-start'
    | 'inset-bottom'
    | 'inset-inline'
    | 'inset-inline-end'
    | 'inset-inline-start'
    | 'inset-left'
    | 'inset-right'
    | 'inset-top'
    | 'isolation'
    | 'iteration-count'
    | 'justify-content'
    | 'justify-items'
    | 'justify-self'
    | 'left'
    | 'letter-spacing'
    | 'line-height'
    | 'list-style-type'
    | 'margin'
    | 'margin-block'
    | 'margin-block-end'
    | 'margin-block-start'
    | 'margin-bottom'
    | 'margin-inline'
    | 'margin-inline-end'
    | 'margin-inline-start'
    | 'margin-left'
    | 'margin-right'
    | 'margin-top'
    | 'matrix3d'
    | 'matrix'
    | 'max-height'
    | 'max-width'
    | 'min-height'
    | 'min-width'
    | 'object-fit'
    | 'object-position'
    | 'opacity'
    | 'order'
    | 'outline'
    | 'outline-color'
    | 'outline-offset'
    | 'outline-style'
    | 'outline-width'
    | 'overflow'
    | 'overflow-x'
    | 'overflow-y'
    | 'padding'
    | 'padding-block'
    | 'padding-block-end'
    | 'padding-block-start'
    | 'padding-bottom'
    | 'padding-inline'
    | 'padding-inline-end'
    | 'padding-inline-start'
    | 'padding-left'
    | 'padding-right'
    | 'padding-top'
    | 'perspective'
    | 'perspective-origin'
    | 'place-content'
    | 'place-items'
    | 'place-self'
    | 'play-state'
    | 'position'
    | 'range'
    | 'range-end'
    | 'range-end-length'
    | 'range-end-name'
    | 'range-start'
    | 'range-start-length'
    | 'range-start-name'
    | 'resize'
    | 'right'
    | 'rotate'
    | 'rotate-3d'
    | 'rotate-3x'
    | 'rotate-3y'
    | 'rotate-3z'
    | 'rotate-x'
    | 'rotate-y'
    | 'rotate-z'
    | 'row-gap'
    | 'scale'
    | 'scale-3d'
    | 'scale-3x'
    | 'scale-3y'
    | 'scale-3z'
    | 'scale-sx'
    | 'scale-sy'
    | 'scale-x'
    | 'scale-y'
    | 'scale-z'
    | 'scroll-margin'
    | 'scroll-margin-block'
    | 'scroll-margin-block-end'
    | 'scroll-margin-block-start'
    | 'scroll-margin-bottom'
    | 'scroll-margin-inline'
    | 'scroll-margin-inline-end'
    | 'scroll-margin-inline-start'
    | 'scroll-margin-left'
    | 'scroll-margin-right'
    | 'scroll-margin-top'
    | 'scroll-padding'
    | 'scroll-padding-block'
    | 'scroll-padding-block-end'
    | 'scroll-padding-block-start'
    | 'scroll-padding-bottom'
    | 'scroll-padding-inline'
    | 'scroll-padding-inline-end'
    | 'scroll-padding-inline-start'
    | 'scroll-padding-left'
    | 'scroll-padding-right'
    | 'scroll-padding-top'
    | 'shape-outside'
    | 'skew'
    | 'skew-sx'
    | 'skew-sy'
    | 'skew-x'
    | 'skew-y'
    | 'space'
    | 'space-x'
    | 'space-y'
    | 'stroke'
    | 'stroke-dasharray'
    | 'stroke-dashoffset'
    | 'stroke-linecap'
    | 'stroke-linejoin'
    | 'stroke-miterlimit'
    | 'stroke-opacity'
    | 'stroke-width'
    | 'table-layout'
    | 'text-align'
    | 'text-decoration-color'
    | 'text-decoration-thickness'
    | 'text-indent'
    | 'text-shadow'
    | 'text-transform'
    | 'timeline'
    | 'timeline-axis'
    | 'timeline-inset'
    | 'timeline-inset-end'
    | 'timeline-inset-start'
    | 'timeline-scroller'
    | 'timing-function'
    | 'top'
    | 'transform'
    | 'transform-origin'
    | 'transform-style'
    | 'translate'
    | 'translate-3d'
    | 'translate-3x'
    | 'translate-3y'
    | 'translate-3z'
    | 'translate-sx'
    | 'translate-sy'
    | 'translate-x'
    | 'translate-y'
    | 'translate-z'
    | 'user-drag'
    | 'user-select'
    | 'vertical-align'
    | 'visibility'
    | 'white-space'
    | 'width'
    | 'word-break'
    | 'z-index'

export type PropertyKeyframes = {
  [K in CSSKeyframeAttribute as `@keyframes jumi-${K}`]: Keyframes
}

export type RevealAnimation = 'reveal-bottom' | 'reveal-left' | 'reveal-right' | 'reveal-top'

export type TailwindTheme
  = | 'accentColor'
    | 'animation'
    | 'aspectRatio'
    | 'backdropBlur'
    | 'backdropBrightness'
    | 'backdropContrast'
    | 'backdropGrayscale'
    | 'backdropHueRotate'
    | 'backdropInvert'
    | 'backdropOpacity'
    | 'backdropSaturate'
    | 'backdropSepia'
    | 'backgroundColor'
    | 'backgroundImage'
    | 'backgroundOpacity'
    | 'backgroundPosition'
    | 'backgroundSize'
    | 'blur'
    | 'borderColor'
    | 'borderOpacity'
    | 'borderRadius'
    | 'borderSpacing'
    | 'borderWidth'
    | 'boxShadow'
    | 'boxShadowColor'
    | 'brightness'
    | 'caretColor'
    | 'colors'
    | 'column-count'
    | 'column-fill'
    | 'column-gap'
    | 'column-rule'
    | 'column-rule-color'
    | 'column-rule-style'
    | 'column-rule-width'
    | 'column-span'
    | 'column-width'
    | 'columns'
    | 'container'
    | 'content'
    | 'contrast'
    | 'cursor'
    | 'data'
    | 'divideColor'
    | 'divideOpacity'
    | 'divideWidth'
    | 'dropShadow'
    | 'fill'
    | 'flex'
    | 'flexBasis'
    | 'flexGrow'
    | 'flexShrink'
    | 'fontFamily'
    | 'fontSize'
    | 'fontWeight'
    | 'gap'
    | 'gradientColorStops'
    | 'grayscale'
    | 'gridAutoColumns'
    | 'gridAutoRows'
    | 'gridColumn'
    | 'gridColumnEnd'
    | 'gridColumnStart'
    | 'gridRow'
    | 'gridRowEnd'
    | 'gridRowStart'
    | 'gridTemplateColumns'
    | 'gridTemplateRows'
    | 'height'
    | 'hueRotate'
    | 'inset'
    | 'invert'
    | 'keyframes'
    | 'letterSpacing'
    | 'lineHeight'
    | 'listStyleType'
    | 'margin'
    | 'maxHeight'
    | 'maxWidth'
    | 'minHeight'
    | 'minWidth'
    | 'objectPosition'
    | 'opacity'
    | 'order'
    | 'outlineColor'
    | 'outlineOffset'
    | 'outlineWidth'
    | 'padding'
    | 'placeholderColor'
    | 'placeholderOpacity'
    | 'ringColor'
    | 'ringOffsetColor'
    | 'ringOffsetWidth'
    | 'ringOpacity'
    | 'ringWidth'
    | 'rotate'
    | 'saturate'
    | 'scale'
    | 'screens'
    | 'scrollMargin'
    | 'scrollPadding'
    | 'sepia'
    | 'skew'
    | 'space'
    | 'spacing'
    | 'stroke'
    | 'strokeWidth'
    | 'supports'
    | 'textColor'
    | 'textDecorationColor'
    | 'textDecorationThickness'
    | 'textIndent'
    | 'textOpacity'
    | 'textUnderlineOffset'
    | 'transformOrigin'
    | 'transitionDelay'
    | 'transitionDuration'
    | 'transitionProperty'
    | 'transitionTimingFunction'
    | 'translate'
    | 'width'
    | 'willChange'
    | 'zIndex'

type CSSKeyframeAttribute
  = 'accent-color'
    | 'align-content'
    | 'align-items'
    | 'align-self'
    | 'alignment-baseline'
    | 'all'
    | 'appearance'
    | 'aspect-ratio'
    | 'backdrop-filter'
    | 'backface-visibility'
    | 'background'
    | 'background-blend-mode'
    | 'block-size'
    | 'border'
    | 'border-collapse'
    | 'border-image'
    | 'border-radius'
    | 'box-shadow'
    | 'color'
    | 'column-fill'
    | 'column-gap'
    | 'column-rule'
    | 'column-span'
    | 'columns'
    | 'display'
    | 'fill'
    | 'filter'
    | 'flex'
    | 'flex-direction'
    | 'font-family'
    | 'font-size'
    | 'font-weight'
    | 'gap'
    | 'height'
    | 'inset'
    | 'justify-content'
    | 'letter-spacing'
    | 'line-height'
    | 'margin'
    | 'max-height'
    | 'max-width'
    | 'min-height'
    | 'min-width'
    | 'opacity'
    | 'order'
    | 'outline'
    | 'outline-offset'
    | 'overflow'
    | 'padding'
    | 'position'
    | 'stroke'
    | 'stroke-dasharray'
    | 'stroke-dashoffset'
    | 'stroke-linecap'
    | 'stroke-linejoin'
    | 'stroke-miterlimit'
    | 'stroke-opacity'
    | 'stroke-width'
    | 'text-align'
    | 'text-shadow'
    | 'transform'
    | 'width'
    | 'z-index'
