export const alignSelf = {
  auto: "auto",
  normal: "normal",
  stretch: "stretch",
  center: "center",
  start: "start",
  end: "end",
  "flex-start": "flex-start",
  "flex-end": "flex-end",
  "self-start": "self-start",
  "self-end": "self-end",
  "anchor-center": "anchor-center",
  baseline: "baseline",
  "first baseline": "first baseline",
  "last baseline": "last baseline",
  "safe center": "safe center",
  "unsafe center": "unsafe center",
};
