export const appearance = {
  none: "none",
  auto: "auto",
  "menulist-button": "menulist-button",
  textfield: "textfield",
  "base-select": "base-select",
  button: "button",
  checkbox: "checkbox",
  listbox: "listbox",
  menulist: "menulist",
  meter: "meter",
  "progress-bar": "progress-bar",
  "push-button": "push-button",
  radio: "radio",
  searchfield: "searchfield",
  "slider-horizontal": "slider-horizontal",
  "square-button": "square-button",
  textarea: "textarea",
};
